force-app/main/default/objects/IFv2_CustomFieldLabel__mdt/IFv2_CustomFieldLabel__mdt.object-meta.xml
<CustomObject>
    <description>Custom field label to display on the page layout in InsightFlow application version 2.0</description>
    <label>Custom Field Label</label>
    <pluralLabel>Custom Field Labels</pluralLabel>
</CustomObject>

force-app/main/default/objects/IFv2_CustomFieldLabel__mdt/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <inlineHelpText>Please enter the API name of the field</inlineHelpText>
    <label>Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_CustomFieldLabel__mdt/fields/FieldLabel__c.field-meta.xml
<CustomField>
    <fullName>FieldLabel__c</fullName>
    <inlineHelpText>Please enter the custom field label to be displayed</inlineHelpText>
    <label>Field Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_CustomFieldLabel__mdt/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <inlineHelpText>Please select the section to which this field belongs</inlineHelpText>
    <label>Section</label>
    <referenceTo>IFv2_Section__mdt</referenceTo>
    <relationshipLabel>Custom Field Labels</relationshipLabel>
    <relationshipName>CustomFieldLabels</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/IFv2_Section__mdt.object-meta.xml
<CustomObject>
    <description>To store different sections to be displayed on the request detail page and workflow detail page in InsightFlow application version 2.0</description>
    <label>Section</label>
    <pluralLabel>Section</pluralLabel>
</CustomObject>

force-app/main/default/objects/IFv2_Section__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Describes the name of the Section.</description>
    <inlineHelpText>Please enter the Name of the section to be displayed on the layout</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Describes whether the section is for Workflow details page or Request details page or Related list.</description>
    <inlineHelpText>Workflow details - For Workflow Detail section
Request details - For Request Detail section
Related lists - For Related List section</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Workflow details</fullName>
                <default>true</default>
                <label>Workflow details</label>
            </value>
            <value>
                <fullName>Request details</fullName>
            </value>
            <value>
                <fullName>Related list</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Used to provide the field set name in in request detail page or set of fields to be displayed in workflow detail page.</description>
    <inlineHelpText>Workflow details - Enter field API names
Request details - Enter the fieldset API name
Related lists - Enter the fieldset API name
To enter the API names of the fields to be displayed. If API names exceeds 255 characters enter custom label name.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/fields/Workflows__c.field-meta.xml
<CustomField>
    <fullName>Workflows__c</fullName>
    <description>Describes to which workflow record this section belongs to.</description>
    <inlineHelpText>Please select the workflow to which the section is related to</inlineHelpText>
    <label>Workflows</label>
    <referenceTo>IFv2_Workflows__mdt</referenceTo>
    <relationshipLabel>Section</relationshipLabel>
    <relationshipName>Section</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflows__mdt/IFv2_Workflows__mdt.object-meta.xml
<CustomObject>
    <description>For storing profile categorization parameters in InsightFlow application version 2.0</description>
    <label>Workflows</label>
    <pluralLabel>Workflows</pluralLabel>
</CustomObject>

force-app/main/default/objects/IFv2_Workflows__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <inlineHelpText>Please enter the Workflow Name</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_FieldSetUtility.cls
/*******************************************************************************************************
* 
* @ Name :IFv2_FieldSetUtility
* @ Purpose :  utility class for generic page layout component
* @ Author: Anoop Ravindran
*
*   Date	        |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   31-10-2018      |  anoop.ravindran@absyz.com	|  1.0          |  Initial Version

*******************************************************************************************************/
public with sharing class IFv2_FieldSetUtility {
    /*method to get fields with custom labels from fieldset name*/
    /*method needs to be removed*/
   /* public static List<IFv2_FieldWrapperClass> getFields(Id recordId, String objectName, String fieldSetName, String sectionId) {
        Schema.SObjectType objectType = null;
        map<String,String> fieldLabelMap = new map<String,String>();
        for(sObject fieldLabel : [	SELECT Id,Section__c,FieldAPIName__c,FieldLabel__c
                                  FROM IFv2_CustomFieldLabel__mdt 
                                  WHERE Section__c = :sectionId ]){
                                      fieldLabelMap.put(String.valueOf(fieldLabel.get('FieldAPIName__c')),String.valueOf(fieldLabel.get('FieldLabel__c')));							
                                  }
        if (recordId != null) {
            objectType = recordId.getSobjectType();
        }
        else if (String.isNotBlank(objectName)) {
            objectType = Schema.getGlobalDescribe().get(objectName);
        }
        
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();
        Schema.FieldSet fieldSet = fieldSetMap.get(fieldSetName);
        List<Schema.FieldSetMember> fieldSetMembers = fieldSet.getFields();
        MAP<String, Schema.SObjectField> fieldMap = objectDescribe.fields.getMap();
        List<IFv2_FieldWrapperClass> fields = new List<IFv2_FieldWrapperClass>();
        for (Schema.FieldSetMember fsm : fieldSetMembers) {
            IFv2_FieldWrapperClass f = new IFv2_FieldWrapperClass(fsm,objectName,null,fieldMap);
            if(fieldLabelMap.containsKey(f.APIName)){
                f.Label = fieldLabelMap.get(f.APIName);
            }
            fields.add(f);
        }
        
        return fields;
    }*/
    /*New method to use*/
    public static List<IFv2_FieldWrapperClass> getFields(Sobject record, String objectName, String fieldSetName, String sectionId) {
        Schema.SObjectType objectType = null;
        map<String,String> fieldLabelMap = new map<String,String>();
        for(sObject fieldLabel : [	SELECT Id,Section__c,FieldAPIName__c,FieldLabel__c
                                  FROM IFv2_CustomFieldLabel__mdt 
                                  WHERE Section__c = :sectionId ]){
                                      fieldLabelMap.put(String.valueOf(fieldLabel.get('FieldAPIName__c')),String.valueOf(fieldLabel.get('FieldLabel__c')));							
                                  }
        if (record != null) {
            objectType = ID.valueOf(String.valueOf(record.get('Id'))).getSobjectType();
        }
        else if (String.isNotBlank(objectName)) {
            objectType = Schema.getGlobalDescribe().get(objectName);
        }
        
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();
        Schema.FieldSet fieldSet = fieldSetMap.get(fieldSetName);
        List<Schema.FieldSetMember> fieldSetMembers = fieldSet.getFields();
        MAP<String, Schema.SObjectField> fieldMap = objectDescribe.fields.getMap();
        List<IFv2_FieldWrapperClass> fields = new List<IFv2_FieldWrapperClass>();
        for (Schema.FieldSetMember fsm : fieldSetMembers) {
            IFv2_FieldWrapperClass f = new IFv2_FieldWrapperClass(fsm,objectName,record,fieldMap);
            if(fieldLabelMap.containsKey(f.APIName)){
                f.Label = fieldLabelMap.get(f.APIName);
            }
            fields.add(f);
        }
        
        return fields;
    }
    /* method to get fields from fieldSet name */
    public static List<IFv2_FieldWrapperClass> getFields(Id recordId, String objectName, String fieldSetName) {
        Schema.SObjectType objectType = null;
        if (recordId != null) {
            objectType = recordId.getSobjectType();
        }
        else if (String.isNotBlank(objectName)) {
            objectType = Schema.getGlobalDescribe().get(objectName);
        }
        
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();
        Schema.FieldSet fieldSet = fieldSetMap.get(fieldSetName);
        List<Schema.FieldSetMember> fieldSetMembers = fieldSet.getFields();
        MAP<String, Schema.SObjectField> fieldMap = objectDescribe.fields.getMap();
        List<IFv2_FieldWrapperClass> fields = new List<IFv2_FieldWrapperClass>();
        for (Schema.FieldSetMember fsm : fieldSetMembers) {
            IFv2_FieldWrapperClass f = new IFv2_FieldWrapperClass(fsm,objectName,null,fieldMap); 
            fields.add(f);
        }
        
        return fields;
    }
    /* method to get fields taking list of field api names as param*/
    public static List<IFv2_FieldWrapperClass> getFieldFromAPINames(string recordId, String objectName, String fieldList) {
        List<IFv2_FieldWrapperClass> fields = new List<IFv2_FieldWrapperClass>();
        Schema.SObjectType objectType = null;
        
        if (recordId != null && recordId!='') {
            objectType = Id.valueOf(recordId).getSobjectType();
        }
        else if (String.isNotBlank(objectName)) {
            objectType = Schema.getGlobalDescribe().get(objectName);
        }
        
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Map<String,Schema.SObjectField > fieldMap = objectDescribe.fields.getMap();
        system.debug('fieldMap:'+fieldMap);
        system.debug('fieldList:'+fieldList);
        for(String field:fieldList.split(',')){
            system.debug('field:'+field);
            IFv2_FieldWrapperClass f = new IFv2_FieldWrapperClass();
            if(fieldMap.containsKey(field)){
                Schema.DescribeFieldResult fieldDescribe = fieldMap.get(field).getDescribe();
                
                f.Label = fieldDescribe.getLabel();
                f.APIName = fieldDescribe.getName();
                f.Type = String.valueOf(fieldDescribe.getType());
                f.HelpText = fieldDescribe.getInlineHelpText();
                fields.add(f);
            }
        }
        system.debug('fields:'+fields);
        return fields;
    }
    
    @AuraEnabled
    public static List<IFv2_FieldWrapperClass> getRequiredFields(String objectName, String RequestType) {
        Schema.SObjectType objectType = null;
        
        List<IFv2_FieldWrapperClass> fields = new List<IFv2_FieldWrapperClass>();
        objectType = Schema.getGlobalDescribe().get(objectName);
        list<IFv2_Section__mdt> Fieldsetlist=[select value__c from IFv2_Section__mdt where Workflows__r.name__c=:RequestType and Type__c='Request details']; 
        map<String,String> fieldLabelMap = new map<String,String>();
        for(sObject fieldLabel : [	SELECT Id,Section__c,FieldAPIName__c,FieldLabel__c
                                  FROM IFv2_CustomFieldLabel__mdt 
                                  WHERE Section__c IN :Fieldsetlist ]){
                                      fieldLabelMap.put(String.valueOf(fieldLabel.get('FieldAPIName__c')),String.valueOf(fieldLabel.get('FieldLabel__c')));							
                                  }
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();
        MAP<String, Schema.SObjectField> fieldMap = objectDescribe.fields.getMap();
        for(IFv2_Section__mdt FieldsetRecord:Fieldsetlist){
            Schema.FieldSet fieldSet = fieldSetMap.get(FieldsetRecord.Value__c.toLowercase());
            List<Schema.FieldSetMember> fieldSetMembers = fieldSet.getFields();
            for (Schema.FieldSetMember fsm : fieldSetMembers) {
                IFv2_FieldWrapperClass f = new IFv2_FieldWrapperClass(fsm,objectName,null,fieldMap);
                if(fieldLabelMap.containsKey(f.APIName)){
                    f.Label = fieldLabelMap.get(f.APIName);
                }
                fields.add(f);
            }    
        }
        return fields;
    }
    /* query */
    public static list<Sobject> recordQuery(String query){
        system.debug('query'+ query);
        list<Sobject> queryData = new list<Sobject>();
        try {
            queryData = Database.query(query);
        } catch(Exception e) {
            IFv2_ExceptionUtilitiesController.exceptionHandler(e);    
        }
        system.debug('queryData:'+queryData);
        return queryData;
    }
    
    public class FieldSetForm {
        /*  @AuraEnabled
public List<IFv2_FieldWrapperClass> Fields { get; set; }

public FieldSetForm() {
Fields = new List<IFv2_FieldWrapperClass>();
}*/
    }
}