force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Workflow__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Workflow__c</fullName>
    <description>The workflow name of the Request object</description>
    <label>Workflow</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Approver for the Workflow Request</inlineHelpText>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/WorkflowId__c.field-meta.xml
<CustomField>
    <fullName>WorkflowId__c</fullName>
    <description>Id of workflow custom setting record</description>
    <label>Workflow Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/IFv2_Workflow__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Details of all the Workflows</description>
    <label>Workflow</label>
</CustomObject>

force-app/main/default/objects/IFv2_Workflow__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <description>Approver</description>
    <inlineHelpText>Enter the Id of the Approver 1</inlineHelpText>
    <label>Approver 1</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/fields/ReminderAfterDays__c.field-meta.xml
<CustomField>
    <fullName>ReminderAfterDays__c</fullName>
    <defaultValue>7</defaultValue>
    <inlineHelpText>Enter the number of days after which the first reminder mail should be sent to the pending Approvers</inlineHelpText>
    <label>Reminder After (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/fields/SubsequentReminderAfter__c.field-meta.xml
<CustomField>
    <fullName>SubsequentReminderAfter__c</fullName>
    <description>The number of days after which subsequent reminders should be sent.</description>
    <inlineHelpText>Enter the number of days after which subsequent reminders should be sent</inlineHelpText>
    <label>Subsequent Reminder After (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>The name of the Workflow</description>
    <inlineHelpText>Enter the name of the Workflow</inlineHelpText>
    <label>Workflow</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IFv2_ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to handle Validation Rules from firing</description>
    <label>By Pass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IFv2_SendReminderMailTest.cls
/***************************************************************************************************************
* 
* @ Name    :   IFv2_SendReminderMailTest
* @ Purpose :   Test data for Send Reminder mail preparation
* @ Author  :   Madhura Vani
* @ Class	: 	IFv2_SendReminderMail
*
*   Date            |  Developer Name               |  Version      |  Changes
* ===============================================================================================================
*   05-01-2019      |  madhuravani.b@absyz.com      |  1.0          |  Initial Version
*   07-05-2019      |  vivek.kothalanka@absyz.com   |  1.1          |  Updated code for changes in Iteartion 3
*
******************************************************************************************************************/
@isTest
public class IFv2_SendReminderMailTest {
    public static Account objAcc ;
    public static Contact objCon ;
    public static list<IFv2_Request__c> lstRequest;
    public static user objUser;
    
    //Test set up method for creating test data
    @testSetup static void createTestData() {
        
        objAcc = IFv2_testDataUtility.createAccount();
        insert objAcc;
        
        objCon = IFv2_testDataUtility.createContact(objAcc);
        insert objCon;
        
        objUser = IFv2_testDataUtility.createUser();
        objUser.IFv2_ByPassValidation__c = true;
        insert objUser;
        
        system.runAs(objUser)
        {
            lstRequest = IFv2_testDataUtility.createRequest();
            insert lstRequest;
        }
        
        objUser.IFv2_ByPassValidation__c = false;
        update objUser;  
    }
    
    public static testmethod void notesData(){ 
        objCon = [select id,lastname from contact limit 1];
        lstRequest = [select id from IFv2_Request__c limit 1];
        objUser = [select id,name from user limit 1];
        lstRequest[0].status__c = 'Submitted';
        lstRequest[0].Workflow__c = 'eSignature';
        update lstRequest[0];
        
        IFv2_Workflow__c objWF = new IFv2_Workflow__c();
        objWF.Name = 'eSignature';
        objWF.Workflow__c = 'eSignature';
        objWF.ReminderAfterDays__c = 7;
        objWF.SubsequentReminderAfter__c = 8;
        list<IFv2_Workflow__c> lstWF = new list<IFv2_Workflow__c>();
        lstWF.add(objWF);
        insert lstWF;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(lstRequest[0].Id); 
        req1.setSubmitterId(UserInfo.getUserId()); 
        
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        system.assertEquals(true,result.isSuccess());
        IFv2_SendReminderMail objSendRem = new IFv2_SendReminderMail();
        database.executeBatch(objSendRem);
    }
    
    public static testMethod void executeTestMethod(){
        
        User userRecord;
        System.runAs(new User(Id=UserInfo.getUserId())) {
            userRecord = IFv2_testDataUtility.createSGStandardUser();
            insert userRecord;
        }
        
        
        IFv2_Request__c requestRecord = new IFv2_Request__c();
        requestRecord.Workflow__c = 'eSignature';
        requestRecord.Status__c= 'submitted';
        requestRecord.Approver1__c = userRecord.Id;
        insert requestRecord;
        
        IFv2_Workflow__c objWF = new IFv2_Workflow__c();
        objWF.Name = 'eSignature';
        objWF.Workflow__c = 'eSignature';
        objWF.ReminderAfterDays__c = 1;
        objWF.SubsequentReminderAfter__c = 1;
        list<IFv2_Workflow__c> lstWF = new list<IFv2_Workflow__c>();
        lstWF.add(objWF);
        insert lstWF;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestRecord.Id); 
        req1.setSubmitterId(UserInfo.getUserId()); 
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        system.assertEquals('Pending',result.getInstanceStatus());
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'test1', Email='test@gamil.com',FirstName = 'Testm', 
                          EmailEncodingKey='UTF-8', LastName='Testlastm', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='test111@gmailtest.com');
        insert u;
        ID candidate;
        ID recipient;
        
        Contact con=new Contact();
        con.lastname='Testing';
        insert con;
        mail.setTargetObjectId(recipient);
        mail.setPlainTextBody('');
        mail.setWhatId(candidate);   
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.setReplyTo('tintu@qburst.com');
        mail.toaddresses=new String[] {'test@gmail.com'};
            mail.setSenderDisplayName('HR Recruiting');
        mail.setSaveAsActivity(false); 
        Test.startTest();
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        Test.stopTest();
        System.assert (result.success, 'InboundEmailResult returned a failure message');
        
        IFv2_SendReminderMail objSendRem = new IFv2_SendReminderMail();
        database.executeBatch(objSendRem);
    }
    
    public static testMethod void executeTestMethod2(){
        
        User userRecord;
        System.runAs(new User(Id=UserInfo.getUserId())) {
            userRecord = IFv2_testDataUtility.createSGStandardUser();
            insert userRecord;
        }
        
        IFv2_Request__c requestRecord = new IFv2_Request__c();
        requestRecord.Workflow__c = 'eSignature';
        requestRecord.Status__c= 'submitted';
        requestRecord.Approver1__c = userRecord.Id;
        insert requestRecord;
        
        IFv2_Workflow__c objWF = new IFv2_Workflow__c();
        objWF.Name = 'eSignature';
        objWF.Workflow__c = 'eSignature';
        objWF.ReminderAfterDays__c = 0;
        objWF.SubsequentReminderAfter__c = 0;
        list<IFv2_Workflow__c> lstWF = new list<IFv2_Workflow__c>();
        lstWF.add(objWF);
        insert lstWF;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestRecord.Id); 
        req1.setSubmitterId(UserInfo.getUserId()); 
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        system.assertEquals(true,result.isSuccess());
        
        IFv2_SendReminderMail objSendRem = new IFv2_SendReminderMail();
        database.executeBatch(objSendRem);
    }
    
    @isTest static void executeTest(){
        Test.startTest();
        IFv2_SendReminderMailSchedulable tsc = new IFv2_SendReminderMailSchedulable();
        String jobId = System.schedule('TetsReminderMailSchedule', '0 0 0 * * ?', tsc);
        Test.stopTest();
        List<CronTrigger> ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        system.assertEquals('0 0 0 * * ?', ct[0].CronExpression);
        Date nextDate = system.today().addDays(1);
        DateTime nextRunDateTime = DateTime.newInstance(nextDate.year(),nextDate.month(),nextDate.day());
        System.assertEquals(1, ct.size());
        System.assertEquals(String.valueOf(nextRunDateTime),String.valueOf(ct[0].NextFireTime));
        
    } 
    
    public static testmethod void notesData2(){ 
        
        IFv2_Workflow__c objWF = new IFv2_Workflow__c();
        objWF.Name = 'eSignature';
        objWF.Workflow__c = 'eSignature';
        objWF.ReminderAfterDays__c = null;
        list<IFv2_Workflow__c> lstWF = new list<IFv2_Workflow__c>();
        lstWF.add(objWF);
        insert lstWF;
        
        objCon = [select id,lastname from contact limit 1];
        lstRequest = [select id from IFv2_Request__c limit 1];
        objUser = [select id,name from user limit 1];
        lstRequest[0].status__c = 'Submitted';
        lstRequest[0].WorkflowId__c = lstWF[0].Id;
        lstRequest[0].Workflow__c = 'eSignature';
        update lstRequest[0];
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(lstRequest[0].Id); 
        req1.setSubmitterId(UserInfo.getUserId()); 
        
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        system.assertEquals(true,result.isSuccess());
        
        IFv2_SendReminderMail objSendRem = new IFv2_SendReminderMail();
        database.executeBatch(objSendRem);
    }
    
    public static testmethod void notesData3(){ 
        
        IFv2_Workflow__c objWF = new IFv2_Workflow__c();
        objWF.Name = 'eSignature';
        objWF.Workflow__c = 'eSignature';
        objWF.ReminderAfterDays__c = 0;
        objWF.SubsequentReminderAfter__c = 0;
        list<IFv2_Workflow__c> lstWF = new list<IFv2_Workflow__c>();
        lstWF.add(objWF);
        insert lstWF;
        
        objCon = [select id,lastname from contact limit 1];
        lstRequest = [select id from IFv2_Request__c limit 1];
        objUser = [select id,name from user limit 1];
        lstRequest[0].status__c = 'Submitted';
        lstRequest[0].WorkflowId__c = lstWF[0].Id;
        lstRequest[0].Workflow__c = 'eSignature';
        update lstRequest[0];
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(lstRequest[0].Id); 
        req1.setSubmitterId(UserInfo.getUserId()); 
        
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        system.assertEquals(true,result.isSuccess());
        
        IFv2_SendReminderMail objSendRem = new IFv2_SendReminderMail();
        database.executeBatch(objSendRem);
    }
    
    
    public static testmethod void notesData4(){ 
        
        IFv2_Workflow__c objWF = new IFv2_Workflow__c();
        objWF.Name = 'eSignature';
        objWF.Workflow__c = 'eSignature';
        objWF.ReminderAfterDays__c = 0;
        objWF.SubsequentReminderAfter__c = 1;
        list<IFv2_Workflow__c> lstWF = new list<IFv2_Workflow__c>();
        lstWF.add(objWF);
        insert lstWF;
        
        objCon = [select id,lastname from contact limit 1];
        lstRequest = [select id from IFv2_Request__c limit 1];
        objUser = [select id,name from user limit 1];
        lstRequest[0].status__c = 'Submitted';
        lstRequest[0].WorkflowId__c = lstWF[0].Id;
        lstRequest[0].Workflow__c = 'eSignature';
        update lstRequest[0];
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(lstRequest[0].Id); 
        req1.setSubmitterId(UserInfo.getUserId()); 
        
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        system.assertEquals(true,result.isSuccess());
        LIST<ProcessInstanceWorkitem> workitemsLIST = new  LIST<ProcessInstanceWorkitem>();
        workitemsLIST = [SELECT OriginalActorId, ActorId, ElapsedTimeInDays,Actor.Name,
                         ProcessInstance.TargetObjectId, createdDate
                         FROM ProcessInstanceWorkitem
                         WHERE ProcessInstance.TargetObjectId =:lstRequest[0].Id ];
        if(workitemsLIST[0] != NULL)
            Test.setCreatedDate(workitemsLIST[0].Id, Datetime.now().addDays(-1));
        
        IFv2_SendReminderMail objSendRem = new IFv2_SendReminderMail();
        database.executeBatch(objSendRem);
    }
    
    public static testmethod void notesData5(){ 
        
        IFv2_Workflow__c objWF = new IFv2_Workflow__c();
        objWF.Name = 'eSignature';
        objWF.Workflow__c = 'eSignature';
        objWF.ReminderAfterDays__c = 1;
        objWF.SubsequentReminderAfter__c = 1;
        list<IFv2_Workflow__c> lstWF = new list<IFv2_Workflow__c>();
        lstWF.add(objWF);
        insert lstWF;
        
        objCon = [select id,lastname from contact limit 1];
        lstRequest = [select id from IFv2_Request__c limit 1];
        objUser = [select id,name from user limit 1];
        lstRequest[0].status__c = 'Submitted';
        lstRequest[0].WorkflowId__c = lstWF[0].Id;
        lstRequest[0].Workflow__c = 'eSignature';
        update lstRequest[0];
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(lstRequest[0].Id); 
        req1.setSubmitterId(UserInfo.getUserId()); 
        
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        system.assertEquals(true,result.isSuccess());
        LIST<ProcessInstanceWorkitem> workitemsLIST = new  LIST<ProcessInstanceWorkitem>();
        workitemsLIST = [SELECT OriginalActorId, ActorId, ElapsedTimeInDays,Actor.Name,
                         ProcessInstance.TargetObjectId, createdDate
                         FROM ProcessInstanceWorkitem
                         WHERE ProcessInstance.TargetObjectId =:lstRequest[0].Id ];
        if(workitemsLIST[0] != NULL)
            Test.setCreatedDate(workitemsLIST[0].Id, Datetime.now().addDays(-2));
        
        IFv2_SendReminderMail objSendRem = new IFv2_SendReminderMail();
        database.executeBatch(objSendRem);
    }
}