force-app/main/default/objects/Account/fields/IFv2_Amount__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Amount__c</fullName>
    <inlineHelpText>Enter the amount in INR</inlineHelpText>
    <label>Total Amount of line item (INR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Quantity__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_ReturnedQuantity__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ReturnedQuantity__c</fullName>
    <label>Returned Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/IFv2_RequestItems.recordType-meta.xml
<RecordType>
    <fullName>IFv2_RequestItems</fullName>
    <active>true</active>
    <description>To be used for storing Request Items for Insightflow 2.0</description>
    <label>Request Items</label>
</RecordType>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Approver10__c.field-meta.xml
<CustomField>
    <fullName>Approver10__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 10</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Approver for the Workflow Request</inlineHelpText>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver3__c.field-meta.xml
<CustomField>
    <fullName>Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver4__c.field-meta.xml
<CustomField>
    <fullName>Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver5__c.field-meta.xml
<CustomField>
    <fullName>Approver5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Provide Approver 5 value.</description>
    <label>Approver 5</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver6__c.field-meta.xml
<CustomField>
    <fullName>Approver6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to provide Approver 6.</description>
    <label>Approver 6</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver7__c.field-meta.xml
<CustomField>
    <fullName>Approver7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 7</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver8__c.field-meta.xml
<CustomField>
    <fullName>Approver8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 8</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver9__c.field-meta.xml
<CustomField>
    <fullName>Approver9__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 9</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ChallanTypeofGatePass__c.field-meta.xml
<CustomField>
    <fullName>ChallanTypeofGatePass__c</fullName>
    <description>Type of Gate Pass</description>
    <inlineHelpText>Enter the type of gate pass for the challan</inlineHelpText>
    <label>Challan - Type of Gate Pass</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Returnable</fullName>
            </value>
            <value>
                <fullName>Non - Returnable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Supplier/Customer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ParentRequest__c.field-meta.xml
<CustomField>
    <fullName>ParentRequest__c</fullName>
    <label>Parent Request</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/RequestExtension1__c.field-meta.xml
<CustomField>
    <fullName>RequestExtension1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is look up for Request Extension1-APAC.</description>
    <label>Request Extension1</label>
    <referenceTo>IFv2_RequestExtension1__c</referenceTo>
    <relationshipLabel>Request Extension1</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/IFv2_RequestExtension1__c.object-meta.xml
<CustomObject>
    <description>Hold the requests of the APAC region</description>
    <label>Request Extension 1 - APAC</label>
    <nameField>
        <label>Request Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Extension 1 - APAC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/IFv2_MaterialControllerTest.cls
/*******************************************************************************************************
* 
* @ Name    	:   IFv2_MaterialControllerTest
* @ Purpose 	:   Test class for IFv2_MaterialController
* @ Author  	:   Anoop Ravindran
* @ Class Name	:	IFv2_MaterialController
*
*   Date        |  Developer Name                   	|  Version      |  Changes
* ======================================================================================================
*   21-05-2019  |  anoop.ravindran@absyz.com.seg     	|  1.0          |  Initial Version
*
*******************************************************************************************************/
@isTest
public class IFv2_MaterialControllerTest {
    @TestSetup
    static void makeData(){
       Profile prof = [SELECT Id FROM Profile WHERE Name='SG Standard User']; 
        User usr = new User(Alias = 'standt', Email='standarduser@testorg.com.seg', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = prof.Id, 
            TimeZoneSidKey='Asia/Kolkata', UserName='standarduser@testorg.com.seg');
        usr.Country = 'India';
        Database.insert(usr);
    }
    public @IsTest
    static void materialControllerTest(){
        
        Test.startTest();
        User usr = [SELECT Id FROM User WHERE UserName = 'standarduser@testorg.com.seg'];
        IFv2_RequestExtension1__c ext = new IFv2_RequestExtension1__c();

        
        
        IFv2_Request__c nonRetreq = new IFv2_Request__c(Workflow__c = Label.CLIFv20199);
        nonRetreq.ChallanTypeofGatePass__c = 'Non - Returnable';
        nonRetreq.Approver1__c = usr.Id;
        nonRetreq.Approver2__c = usr.Id;
        nonRetreq.Approver3__c = usr.Id;
        nonRetreq.Approver4__c = usr.Id;
        nonRetreq.Approver8__c = usr.Id;
        nonRetreq.Approver9__c = usr.Id;
        nonRetreq.Approver10__c = usr.Id;
        nonRetreq.Customer_Name__c = 'Test Customer';
        Database.insert(ext);
        System.assertNotEquals(null, ext.Id);
        
        nonRetreq.RequestExtension1__c = ext.Id;
        Database.insert(nonRetreq);
        System.assertNotEquals(null, nonRetreq.Id);
        
        Id acctRecType = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordtypeinfosbydevelopername().get('IFv2_RequestItems').getRecordTypeId();
        Account mat = new Account(RecordTypeId = acctRecType);
        mat.Name = 'Test Material';
        mat.IFv2_Quantity__c = 200;
        mat.IFv2_Amount__c = 15000;
        mat.IFv2_Request__c = nonRetreq.Id;
        Database.insert(mat);
        System.assertNotEquals(null, mat.Id);

        IFv2_MaterialController.MaterialDisplayWrapper dispWrapper = IFv2_MaterialController.getMaterialDetails(nonRetreq.Id);
        System.assertEquals(1, dispWrapper.materialDetailLIST.size());
        System.assertEquals(true, dispWrapper.isParent);

        IFv2_MaterialController.MaterialWrapper wrap = new IFv2_MaterialController.MaterialWrapper();
        wrap.currentQty = 100;
        wrap.material = mat;
        LIST<IFv2_MaterialController.MaterialWrapper> wrapList = IFv2_MaterialController.updateMaterialDetails(nonRetreq.Id, new LIST<IFv2_MaterialController.MaterialWrapper>{wrap});
        
        wrap = wrapList[0];
        system.assertEquals(100, wrap.material.IFv2_ReturnedQuantity__c);
        wrap.currentQty = 150;
        wrapList =  IFv2_MaterialController.updateMaterialDetails(nonRetreq.Id, new LIST<IFv2_MaterialController.MaterialWrapper>{wrap});
        system.assertEquals(null, wrapList);

        nonRetreq.Workflow__c = Label.CLIFv20200;
        nonRetreq.ChallanTypeofGatePass__c = 'Returnable';
        Database.update(nonRetreq);
        dispWrapper = IFv2_MaterialController.getMaterialDetails(nonRetreq.Id);
        System.assertEquals(1, dispWrapper.materialDetailLIST.size());
        System.assertEquals(false, dispWrapper.isParent);
        Test.stopTest();
        
    }
    
    
    public @IsTest
    static void requestTriggerTest(){
        
        Test.startTest();
        User usr = [SELECT Id FROM User WHERE UserName = 'standarduser@testorg.com.seg'];
        IFv2_RequestExtension1__c ext = new IFv2_RequestExtension1__c();

        
        
        IFv2_Request__c req = new IFv2_Request__c(Workflow__c = Label.CLIFv20199);
        req.ChallanTypeofGatePass__c = 'Non - Returnable';
        req.Approver1__c = usr.Id;
        req.Approver2__c = usr.Id;
        req.Approver3__c = usr.Id;
        req.Approver4__c = usr.Id;
        req.Approver5__c = usr.Id;
        req.Approver6__c = usr.Id;
        req.Approver7__c = usr.Id;
        req.Approver8__c = usr.Id;
        req.Approver9__c = usr.Id;
        req.Approver10__c = usr.Id;
        Database.insert(ext);
        System.assertNotEquals(null, ext.Id);
        req.Status__c = 'Submitted';
        req.RequestExtension1__c = ext.Id;
        Database.insert(req);
        System.assertNotEquals(null, req.Id);
        
        Id acctRecType = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordtypeinfosbydevelopername().get('IFv2_RequestItems').getRecordTypeId();
        Account mat = new Account(RecordTypeId = acctRecType);
        mat.Name = 'Test Material';
        mat.IFv2_Quantity__c = 200;
        mat.IFv2_Amount__c = 15000;
        mat.IFv2_Request__c = req.Id;
        Database.insert(mat);
        System.assertNotEquals(null, mat.Id);
        req.ChallanTypeofGatePass__c = 'Returnable';
        req.Status__c = 'Approved';
        Database.update(req);
        
        Contact record = new Contact();
        record.AccountId = mat.Id;
        record.LastName = 'Test Contact';
        insert record;
        
        LIST<IFv2_Request__c> parentReq = [select Id,parentRequest__c FROM IFv2_Request__c where Id = :req.Id];
        LIST<IFv2_Request__c> childReq = [select Id,parentRequest__c FROM IFv2_Request__c where parentRequest__c = :req.Id];
        System.assertEquals(1,childReq.size());
        System.assertEquals(childReq[0].Id,parentReq[0].parentRequest__c);
        System.assertEquals(parentReq[0].Id,childReq[0].parentRequest__c);
        
        Test.stopTest();
        
    }
}