force-app/main/default/objects/Account/fields/IFv2_Workflow__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Workflow__c</fullName>
    <description>The workflow name of the Request object</description>
    <label>Workflow</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/IFv2_Workflow__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Details of all the Workflows</description>
    <label>Workflow</label>
</CustomObject>

force-app/main/default/objects/IFv2_Workflow__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>The name of the Workflow</description>
    <inlineHelpText>Enter the name of the Workflow</inlineHelpText>
    <label>Workflow</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IFv2_ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to handle Validation Rules from firing</description>
    <label>By Pass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IFv2_UpdateAccountTypeTest.cls
/*******************************************************************************************************
* 
* @ Name 			: IFv2_UpdateAccountTypeTest
* @ Author			: Vivek
* @ Test Class Name : IFv2_UpdateAccountName
*
*   Date        |  Developer Name                 |  Version      |  Changes
* ======================================================================================================
*   01-07-2019  |  vivek.kothalanka@absyz.com     |  1.0          |  Initial Version

*******************************************************************************************************/
@istest
public class IFv2_UpdateAccountTypeTest {
    
    public static testmethod void testMethod1() {
        
        Test.startTest();
        
        IFv2_Workflow__c workflowRecord = IFv2_testDataUtility.createWorkflowCustomSetting();
        
        workflowRecord.Name = 'eSignature';
        workflowRecord.Workflow__c = 'eSignature';
        insert workflowRecord;
        System.assertEquals(true, workflowRecord != Null);
        
        User loggedInUser = IFv2_testDataUtility.createUser();
        loggedInUser.IFv2_ByPassValidation__c = true;
        insert loggedInUser;
        System.assertEquals(true, loggedInUser != Null);
        
        system.runas(loggedInUser){
            IFv2_WorkflowListviewController.createRequestRecord(workflowRecord);
        }
        loggedInUser.IFv2_ByPassValidation__c = false;
        update loggedInUser;
        System.assertEquals(true, loggedInUser.IFv2_ByPassValidation__c == false);
        
        Account accountRecord = [SELECT Id, Name,RecordTypeId,RecordType.Name 
                                 FROM Account LIMIT 1];
        
        accountRecord.ownerId = UserInfo.getUserID();
        accountRecord.Name =  accountRecord.Name.replace('ACC','INF');
        update accountRecord;
        
        IFv2_UpdateAccountNameBatch obj = new IFv2_UpdateAccountNameBatch();
        DataBase.executeBatch(obj); 
        
        Test.stopTest();
    }
    
    public static testmethod void testMethod2() {
        
        Test.startTest();
        
        IFv2_Workflow__c workflowRecord = IFv2_testDataUtility.createWorkflowCustomSetting();
        
        workflowRecord.Name = 'eSignature';
        workflowRecord.Workflow__c = 'eSignature';
        insert workflowRecord;
        System.assertEquals(true, workflowRecord != Null);
        
        User loggedInUser = IFv2_testDataUtility.createUser();
        loggedInUser.IFv2_ByPassValidation__c = true;
        insert loggedInUser;
        System.assertEquals(true, loggedInUser != Null);
        
        system.runas(loggedInUser){
            IFv2_WorkflowListviewController.createRequestRecord(workflowRecord);
        }
        loggedInUser.IFv2_ByPassValidation__c = false;
        update loggedInUser;
        System.assertEquals(true, loggedInUser.IFv2_ByPassValidation__c == false);
        
        Account accountRecord = [SELECT Id, Name,RecordTypeId,RecordType.Name 
                                 FROM Account LIMIT 1];
        Id AccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        system.debug(AccountRecordTypeId);
        accountRecord.RecordTypeId = AccountRecordTypeId;
        accountRecord.ownerId = UserInfo.getUserID();
        accountRecord.Name =  accountRecord.Name.replace('ACC','INF');
        update accountRecord;          
        
        IFv2_UpdateAccountNameBatch obj = new IFv2_UpdateAccountNameBatch();
        DataBase.executeBatch(obj); 
        
        Test.stopTest();
    }
}