force-app/main/default/objects/Account/fields/IFv2_NotificationNo__c.field-meta.xml
<CustomField>
    <fullName>IFv2_NotificationNo__c</fullName>
    <description>Used in Concession Workflow</description>
    <label>Notification No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Workflow__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Workflow__c</fullName>
    <description>The workflow name of the Request object</description>
    <label>Workflow</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_PredefinedWorkflowFields__mdt/IFv2_PredefinedWorkflowFields__mdt.object-meta.xml
<CustomObject>
    <description>To map the predefined IFv2_Workflow__c custom settings fields with the IFv2_Request__c object in InsightFlow application version 2.0</description>
    <label>Predefined Mapping</label>
    <pluralLabel>Predefined Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IFv2_PredefinedWorkflowFields__mdt/fields/RequestFieldAPI__c.field-meta.xml
<CustomField>
    <fullName>RequestFieldAPI__c</fullName>
    <description>IFv2_Request__c object field Api</description>
    <inlineHelpText>Please enter the API name of the IFv2_Request__c object field to be mapped</inlineHelpText>
    <label>Request Field API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_PredefinedWorkflowFields__mdt/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <inlineHelpText>Please select the workflow to which the Predefined Mapping is related to</inlineHelpText>
    <label>Workflow</label>
    <referenceTo>IFv2_Workflows__mdt</referenceTo>
    <relationshipLabel>Predefined Mappings</relationshipLabel>
    <relationshipName>PredefinedMappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IFv2_PredefinedWorkflowFields__mdt/fields/WorkflowField__c.field-meta.xml
<CustomField>
    <fullName>WorkflowField__c</fullName>
    <description>IFv2_Workflow__c custom settings field apis</description>
    <inlineHelpText>Please enter the API name of the IFv2_Workflow__c custom settings field to be mapped</inlineHelpText>
    <label>Workflow Field API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>AccountRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/DueDateofReturn__c.field-meta.xml
<CustomField>
    <fullName>DueDateofReturn__c</fullName>
    <label>Due Date of Return</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Local_Expert_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Expert_Id__c</fullName>
    <label>Local Expert Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SGDE-St (Weilimdorf)</fullName>
            </value>
            <value>
                <fullName>SGDE-Hi (Hildesheim)</fullName>
            </value>
            <value>
                <fullName>SDGE-Ig (Ingolstadt)</fullName>
            </value>
            <value>
                <fullName>SGDE-Mu (München)</fullName>
            </value>
            <value>
                <fullName>SGES-Tr (Treto)</fullName>
            </value>
            <value>
                <fullName>SGHU-Mc (Miskolc)</fullName>
            </value>
            <value>
                <fullName>SGNA-Le (Lerma)</fullName>
            </value>
            <value>
                <fullName>SGNA-Nv (Novi)</fullName>
            </value>
            <value>
                <fullName>SGBR-It (Itupeva)</fullName>
            </value>
            <value>
                <fullName>SGCN-Cs (Changsha)</fullName>
            </value>
            <value>
                <fullName>SGCN-Cc (Changchun)</fullName>
            </value>
            <value>
                <fullName>SGIN-Nh (Naganathapura)</fullName>
            </value>
            <value>
                <fullName>SGIN-Hs (Hassan)</fullName>
            </value>
            <value>
                <fullName>SGIN-Ci (Chennai)</fullName>
            </value>
            <value>
                <fullName>SGFR-Dy (Drancy)</fullName>
            </value>
            <value>
                <fullName>SGJP-Yh (Yokohama)</fullName>
            </value>
            <value>
                <fullName>SGKR-Yo (Yongin-si)</fullName>
            </value>
            <value>
                <fullName>SGIT-Tn (Torino)</fullName>
            </value>
            <value>
                <fullName>SGPT-Vc (Vila do Conde)</fullName>
            </value>
            <value>
                <fullName>SGZA-Bi (Brits)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/RequestExtension1__c.field-meta.xml
<CustomField>
    <fullName>RequestExtension1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is look up for Request Extension1-APAC.</description>
    <label>Request Extension1</label>
    <referenceTo>IFv2_RequestExtension1__c</referenceTo>
    <relationshipLabel>Request Extension1</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/RequestExtension2__c.field-meta.xml
<CustomField>
    <fullName>RequestExtension2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is look up for Request Extension2-EMEA</description>
    <label>Request Extension2</label>
    <referenceTo>IFv2_RequestExtension2__c</referenceTo>
    <relationshipLabel>Request Extension2</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/RequestExtension3__c.field-meta.xml
<CustomField>
    <fullName>RequestExtension3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is look up for Request Extension3 - NALA</description>
    <label>Request Extension3</label>
    <referenceTo>IFv2_RequestExtension3__c</referenceTo>
    <relationshipLabel>Request Extension3</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Scan__c.field-meta.xml
<CustomField>
    <fullName>Scan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the ICO request to its related SCAN record</description>
    <label>Scan</label>
    <referenceTo>Scan__c</referenceTo>
    <relationshipLabel>ICO Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/WorkflowId__c.field-meta.xml
<CustomField>
    <fullName>WorkflowId__c</fullName>
    <description>Id of workflow custom setting record</description>
    <label>Workflow Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/IFv2_RequestExtension1__c.object-meta.xml
<CustomObject>
    <description>Hold the requests of the APAC region</description>
    <label>Request Extension 1 - APAC</label>
    <nameField>
        <label>Request Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Extension 1 - APAC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_RequestExtension1__c/fields/DueDateofReturn__c.field-meta.xml
<CustomField>
    <fullName>DueDateofReturn__c</fullName>
    <label>Due Date of Return</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/fields/TotalNetBookValue__c.field-meta.xml
<CustomField>
    <fullName>TotalNetBookValue__c</fullName>
    <description>Used as a Roll up summary fiield in China MAE WF</description>
    <label>Total Net Book Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/fields/TotalOriginalValue__c.field-meta.xml
<CustomField>
    <fullName>TotalOriginalValue__c</fullName>
    <description>Used to populate the Rollup summary field of Original value</description>
    <label>Total Original Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/fields/WorkflowName__c.field-meta.xml
<CustomField>
    <fullName>WorkflowName__c</fullName>
    <label>WorkflowName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension2__c/IFv2_RequestExtension2__c.object-meta.xml
<CustomObject>
    <description>Hold the requests of the EMEA region</description>
    <label>Request Extension 2 - EMEA</label>
    <nameField>
        <label>Request Extension 2 - EMEA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Extension 2 - EMEA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_RequestExtension3__c/IFv2_RequestExtension3__c.object-meta.xml
<CustomObject>
    <description>Hold the requests of the NALA region.</description>
    <label>Request Extension 3 - NALA</label>
    <nameField>
        <label>Request Extension 3 - NALA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Extension 3 - NALA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Workflow__c/IFv2_Workflow__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Details of all the Workflows</description>
    <label>Workflow</label>
</CustomObject>

force-app/main/default/objects/IFv2_Workflow__c/fields/LocalExpert__c.field-meta.xml
<CustomField>
    <fullName>LocalExpert__c</fullName>
    <inlineHelpText>Enter the Local Expert ID of the workflow based on the country.</inlineHelpText>
    <label>Local Expert</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>The name of the Workflow</description>
    <inlineHelpText>Enter the name of the Workflow</inlineHelpText>
    <label>Workflow</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_DmlController.cls
/*******************************************************************************************************
* 
* @ Name   	 		: IFv2_DmlController
* @ Purpose 		: Base controller for all the DML queries
* @ Author  		: Pradeep Chary
* Test class name	: IFv2_FieldSetFormControllerTest 
*
*   Date        |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   31-10-2018  |  pradeep.chary@absyz.com      |  1.0          |  Initial Version
*   08-09-2018  |  madhuravani.b@absyz.com      |  1.1          |  Generic DML operations
*   22/04-2019	|  vivek.kothalanka@absyz.com	|  1.2			|  Added logic to insert Account Share Records
*
*******************************************************************************************************/

public without sharing class IFv2_DmlController {
    
    /* To insert a Request record and an Account record */
    public static Id insertRequestRecord(IFv2_Workflow__c workflow) {
        IFv2_Request__c insertedRequest = new IFv2_Request__c();
        try {
            /* Request record insertion - Start */
            IFv2_Request__c request = new IFv2_Request__c();
            request.Workflow__c = workflow.Workflow__c;
            request.put('WorkflowId__c',workflow.Id);
			request.put('Local_Expert_Id__c',workflow.LocalExpert__c);
            /* list for mapping of roles from workflow detail page to request detail page*/
            LIST<IFv2_PredefinedWorkflowFields__mdt> predefinedFieldLIST = IFv2_UtilsController.getPredefinedFields(workflow.Workflow__c);
            if(!predefinedFieldLIST.isEmpty()) {
                for(IFv2_PredefinedWorkflowFields__mdt iterator : predefinedFieldLIST) {
                    request.put(iterator.RequestFieldApi__c, workflow.get(iterator.WorkflowField__c));
                }
            }
            
            GenericDMLOperation(request, 'insert');		//Request insert
            /* Request record insertion - End */
            
            String Region = IFv2_UtilsController.getWorkflows(workflow.Workflow__c); //Gets the region of the executed Workflow
            if(request.Id != null){
                insertedRequest = IFv2_UtilsController.getInsertedRequest(request.Id);
            }
            if(insertedRequest != null){
                if(Region == 'All') {
                    
                    /* Extension record Account insertion - Start */
                    Account accountRecord = new Account();
                    accountRecord.put('recordtypeid', Schema.SObjectType.Account.getRecordTypeInfosByName().get('Request Extension').getRecordTypeId());
                    
                    accountRecord.Name = insertedRequest.Name.replace('INF','ACC');
                    accountRecord.IFv2_Request__c = insertedRequest.Id;
                    accountRecord.IFv2_Workflow__c = insertedRequest.Workflow__c;
                    accountRecord.Plant__c = 'SGNA';
                    GenericDMLOperation(accountRecord, 'insert');	//Insert Account as an Extension 
                    insertedRequest.Account__c = accountRecord.Id;
                    /* Extension record Account insertion - End */
                    
                } else if(Region == 'APAC') {
                    
                    /* Extension record APAC insertion - Start */
                    IFv2_RequestExtension1__c Extension1 = new IFv2_RequestExtension1__c();
                    Extension1.Name = insertedRequest.Name;
                    Extension1.WorkflowName__c = insertedRequest.Workflow__c;
                    GenericDMLOperation(Extension1, 'insert');	//Insert IFv2_RequestExtension1__c as an Extension
                    insertedRequest.RequestExtension1__c = Extension1.Id;
                    /* Extension record APAC insertion - End */
                    
                } else if(Region == 'EMEA') {
                    
                    /* Extension record EMEA insertion - Start */
                    IFv2_RequestExtension2__c Extension2 = new IFv2_RequestExtension2__c();
                    Extension2.Name = insertedRequest.Name;
                    Extension2.WorkflowName__c = insertedRequest.Workflow__c;
                    GenericDMLOperation(Extension2, 'insert');		//Insert IFv2_RequestExtension2__c as an Extension
                    insertedRequest.RequestExtension2__c = Extension2.Id;
                    /* Extension record EMEA insertion - End */
                    
                } else if(Region == 'NALA') {
                    
                    /* Extension record NALA insertion - Start */
                    IFv2_RequestExtension3__c Extension3 = new IFv2_RequestExtension3__c();
                    Extension3.Name = insertedRequest.Name;
                    Extension3.WorkflowName__c = insertedRequest.Workflow__c;
                    GenericDMLOperation(Extension3, 'insert');		//Insert IFv2_RequestExtension3__c as an Extension
                    insertedRequest.RequestExtension3__c = Extension3.Id;
                    /* Extension record NALA insertion - End */
                }
                
                GenericDMLOperation(insertedRequest, 'update');		//Update Inserted request with the extension Id
            }
        } catch(DMLException de) {
            IFv2_ExceptionUtilitiesController.exceptionHandler(de);
        } catch(Exception e) {
            IFv2_ExceptionUtilitiesController.exceptionHandler(e);
        }
        
        if(insertedRequest != null) {
            return insertedRequest.Id;
        } else {
            return null;
        }
    }
    
    /* To clone a Request record */
    public static Id cloneRequestRecord(IFv2_Request__c requestRecord,MAP<String,LIST<String>> extFieldMap) {
        String extObjectName;
        String extRecordId;
        String extRelName;
        LIST<String> fieldList = new LIST<String>{'Id'};
            if(requestRecord != null){
                if(requestRecord.get('RequestExtension1__c')!=null) {    //APAC
                    extRelName = 'RequestExtension1__c';
                    extObjectName = 'IFv2_RequestExtension1__c';
                    extRecordId = String.valueOf(requestRecord.get('RequestExtension1__c'));
                    if(extFieldMap.containsKey('RequestExtension1__c')) {
                        fieldList = extFieldMap.get('RequestExtension1__c');    //Adding fields on Extension 1 to clone
                    }
                } else if(requestRecord.get('RequestExtension2__c')!=null) {    //EMEA
                    extRelName = 'RequestExtension2__c';
                    extObjectName = 'IFv2_RequestExtension2__c';
                    extRecordId = String.valueOf(requestRecord.get('RequestExtension2__c'));
                    if(extFieldMap.containsKey('RequestExtension2__c')) {
                        fieldList = extFieldMap.get('RequestExtension2__c');    //Adding fields on Extension 2 to clone
                    }
                } else if(requestRecord.get('RequestExtension3__c')!=null) {    //NALA
                    extRelName = 'RequestExtension3__c';
                    extObjectName = 'IFv2_RequestExtension3__c';
                    extRecordId = String.valueOf(requestRecord.get('RequestExtension3__c'));
                    if(extFieldMap.containsKey('RequestExtension3__c')) {
                        fieldList = extFieldMap.get('RequestExtension3__c');    //Adding fields on Extension 3 to clone
                    }
                } else if(requestRecord.get('Account__c')!=null) {
                    extRelName = 'Account__c';
                    extObjectName = 'Account';
                    extRecordId = String.valueOf(requestRecord.get('Account__c'));
                    if(extFieldMap.containsKey('Account__c')) {
                        fieldList = extFieldMap.get('Account__c');    //Adding fields on Account to clone
                    }
                }
                for(String field:fieldList){
                    system.debug(field);
                }
                GenericDMLOperation(requestRecord, 'insert');    //inserting the new cloned request after mapping fields from the parent request
                if(requestRecord.Id != null){
                    if(extRecordId != null) {
                        SObject insertedRecord = IFv2_UtilsController.getInsertedRequest(requestRecord.Id);    //getting the cloned record
                        MAP<String,Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get(extObjectName).getDescribe().fields.getMap();
                        String query = 'SELECT ' + String.join(fieldList,',') + 
                            ' FROM ' + extObjectName + ' WHERE Id=\'' + extRecordId + '\'';
                        LIST<SObject> recList = Database.query(query);    //querying for extension fields to insert values
                        if(!recList.isEmpty()) {
                            SObject extRecord = recList[0];
                            extRecord.put('Id', null);
                            extRecord.put('OwnerId',UserInfo.getUserId());
                            extRecord.put('Name',insertedRecord.get('Name'));
                            
                            // To Nullify values on clone 
                            if(extObjectName == 'IFv2_RequestExtension1__c') {
                                extRecord.put('TotalOriginalValue__c', null);
                                extRecord.put('TotalNetBookValue__c', null);
                                if(requestRecord.Workflow__c == Label.CLIFv20199 || requestRecord.Workflow__c == Label.CLIFv20200){
                                    extRecord.put('DueDateofReturn__c',null);
                                }
                            } else if(extObjectName == 'Account') {
                                extRecord.put('IFv2_NotificationNo__c', null);
                            }
                            GenericDMLOperation(extRecord, 'insert');    //inserting extension object fields
                            requestRecord.put(extRelName,extRecord.get('Id'));    //setting extension id to the new request record
                        }
                        GenericDMLOperation(requestRecord, 'update');    //updating the new request after setting the extension id
                    }
                }
                /*Check for ICO requests other than ICO 6 and submit for approval immediately after cloning*/
                if(requestRecord.Id != null){
                    if(requestRecord.Workflow__c.containsIgnoreCase(system.label.CLIFv20136) && !requestRecord.Workflow__c.equals(system.label.CLIFv20250)){
                    	Sobject SobjectTypeRecord = (Sobject)requestRecord;
                		LIST<IFv2_HeaderController.ApproverSectionWrapper> approverSectionList = IFv2_HeaderController.getApproverSectionWrapper(requestRecord.Id, requestRecord.Workflow__c);
                		System.debug('Approver Section::'+approverSectionList);
                		String statusOfSubmition = IFv2_HeaderController.submitForApproval(SobjectTypeRecord,approverSectionList);
                    }
                }
                return requestRecord.Id;
            }
        else return null;
    }
    
    /* To Delete a Request record */
    public static void deleteRequestRecord (id requestId) {
        IFv2_Request__c requestRecord = new IFv2_Request__c();
        if(requestId != null) {
            requestRecord.Id = requestId;
            GenericDMLOperation(requestRecord, 'delete');    //deleting the request record
        }
    }
    
    /* To Update a Request record */
    public static void updateRequestRecord (IFv2_Request__c requestRecord) {
        if(requestRecord != null){
            GenericDMLOperation(requestRecord, 'update');
        }
    }
    
    /* To change status followed/unfollow */
    public static Boolean followRecord(String recordId,Boolean isFollowed) {
        if(!String.isBlank(recordId)){
            LIST<EntitySubscription> EntityLIST = new LIST<EntitySubscription>(); 
            if(!isFollowed) {
                EntitySubscription entitysubscription = new EntitySubscription(parentId = recordId, SubscriberId = UserInfo.getUserId());
                GenericDMLOperation(entitysubscription, 'insert');
            } else if(isFollowed) {
                EntityLIST = [SELECT id FROM EntitySubscription 
                              WHERE parentId =: recordId AND subscriberId =: UserInfo.getUserId() LIMIT 1000];
                if(!EntityLIST.isEmpty()){
                    GenericListDMLOperation(EntityLIST, 'delete');
                }
            }
            return !isFollowed;
        }
        else return false;
    }
    
    /* To insert Request Share records Used to insert share records */
    public static void insertShareRecords(LIST<IFv2_Request__Share> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'insert');
        }
    }
    
    /* To insert Request Share records Used to insert share records */
    public static void insertShareRecordsAPAC(LIST<IFv2_RequestExtension1__Share> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'insert');
        }
    }
    
    /* To insert Request Share records Used to insert share records */
    public static void insertShareRecordsEMAE(LIST<IFv2_RequestExtension2__Share> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'insert');
        }
    }
    
    /* To insert Request Share records Used to insert share records */
    public static void insertShareRecordsNALA(LIST<IFv2_RequestExtension3__Share> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'insert');
        }
    }
    
    public static void insertAccountShare(LIST<AccountShare> shareRecordsLIST) {
        
        if(!shareRecordsLIST.isEmpty()){
            GenericListDMLOperation(shareRecordsLIST, 'insert');
        }
    }
    
    /* To delete Request Share records */
    public static void deleteShareRecords(LIST<IFv2_Request__Share> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'delete');
        }
    }
    
    /* To delete Requestextension Share records Used to delete share records */
    public static void deleteShareRecordsAPAC(LIST<IFv2_RequestExtension1__Share> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'delete');
        }
    }
    
    /* To delete Requestextension Share records Used to delete share records */
    public static void deleteShareRecordsEMAE(LIST<IFv2_RequestExtension2__Share> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'delete');
        }
    }
    /* To delete Requestextension Share records Used to delete share records */
    public static void deleteShareRecordsNALA(LIST<IFv2_RequestExtension3__Share> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'delete');
        }
    }
    /* To delete Account Share records */
    public static void deleteShareRecordsAccount(LIST<AccountShare> shareRecordsList) {
        if(!shareRecordsList.isEmpty()){
            GenericListDMLOperation(shareRecordsList, 'delete');
        }
    }
    
    
    /* To delete Accountecords */
    public static void deleteAccountRecords(LIST<Account> AccountList) {
        if(!AccountList.isEmpty()){
            GenericListDMLOperation(AccountList, 'delete');
        }
    }
    
    /* To insert Accountecords */
    public static void insertAccountRecords(LIST<Account> AccountList) {
        if(!AccountList.isEmpty()){
            GenericListDMLOperation(AccountList, 'insert');
        }
    }
    
    /* Start of Iteration 3 changes */
    /* To update Account records */
    public static void updateAccountRecords(LIST<Account> AccountList) {
        if(!AccountList.isEmpty()){
            GenericListDMLOperation(AccountList, 'update');
        }
    }
    
    /* Method to update extension records */
    public static void UpdateExtensionOnerecords(LIST<IFv2_RequestExtension1__c> ExtensionList) {
        if(!ExtensionList.isEmpty()){
            GenericListDMLOperation(ExtensionList, 'update');
        }
    }
    
    /* End of iteration 3 changes */
    
    /* Update the ProcessInstance after Reassigning */
    public static void updateActor(LIST<ProcessInstanceWorkitem> approvalItem) {
        //Database.saveResult[] srList = Database.update(approvalItem, false);
        if(!approvalItem.isEmpty()){
            GenericListDMLOperation(approvalItem, 'update');
        }
    }
    
    /*Method to Insert users to permissionsets. */
    public static void insertPermissionSetUsers(LIST<PermissionSetAssignment> PermissionSetList) {
        if(!PermissionSetList.isEmpty())
            GenericListDMLOperation(PermissionSetList, 'insert');
    }
    
    /* Method to update user records */
    public static void updateUsers(LIST<User> UserRecords) {
        if(!UserRecords.isEmpty()){
            GenericListDMLOperation(UserRecords, 'update');
        }
    }
    
    /* Delete Permission set Assignment if user record is updated. */
    public static void deleteAssignment(LIST<PermissionSetAssignment> assignmentlist) {
        if(!assignmentlist.isEmpty()){
            GenericListDMLOperation(assignmentlist, 'delete');
        }
    }
    
    /* Start of Iteration 3 changes */
    /* Added to update Scan records */
    public static void UpdateScanRecord(LIST<Scan__c> ScanRecords) {
        if(!ScanRecords.isEmpty()){
            GenericListDMLOperation(ScanRecords, 'update');
        }
    }
    /* End of Iteration 3 changes */
    
    /* Generic DML method which inserts,update,delete and upserts the records */
    public static void GenericListDMLOperation(LIST<SObject> recordLIST, String operation) {
        String UNABLE_TO_LOCK_ROW = System.Label.CLIFv20155;
        Integer MAX_TRIES = Integer.valueOf(System.Label.CLIFv20188);
        if(!recordLIST.isEmpty()){
            if(operation == 'insert') {
                try {
                    Database.SaveResult[] result = Database.insert(recordLIST);
					system.debug('result--insert' + result);                    
                } catch(DMLException de) {
                    IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                }
            } else if(operation == 'update') {
                Integer count = 0;
                while(count < MAX_TRIES) {
                    try {
                        Database.SaveResult[] result = Database.update(recordLIST);
                        break;
                    } catch(DMLException de) {
                        if(de.getMessage().contains(UNABLE_TO_LOCK_ROW)) {
                            count++;
                        } else {
                            count = MAX_TRIES;
                            IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                        } 
                    }
                }
            } else if(operation == 'delete') {
                try {
                    Database.DeleteResult[] result = Database.delete(recordLIST);
                } catch(DMLException de) {
                    IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                }
            } else if(operation == 'upsert') {
                Integer count = 0;
                while(count < MAX_TRIES) {
                    try {
                        Database.UpsertResult[] result = Database.upsert(recordLIST);
                        break;
                    } catch(DMLException de) {
                        if(de.getMessage().contains(UNABLE_TO_LOCK_ROW)) {
                            count++;
                        } else {
                            count = MAX_TRIES;
                            IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                        }
                    }
                }
            }
        }
    }
    
    /* Generic DML method which inserts,update,delete and upserts the records */
    public static void GenericDMLOperation(SObject record, String operation) {
        String UNABLE_TO_LOCK_ROW = System.Label.CLIFv20155;
        Integer MAX_TRIES = Integer.valueOf(System.Label.CLIFv20188);
        if(record != null){
            if(operation == 'insert') {
                try {
                    Database.SaveResult result = Database.insert(record);
                } catch(DMLException de) {
                    IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                }
            } else if(operation == 'update') {
                Integer count = 0;
                while(count < MAX_TRIES) {
                    try {
                        Database.SaveResult result = Database.update(record);
                        break;
                    } catch(DMLException de) {
                        if(de.getMessage().contains(UNABLE_TO_LOCK_ROW)) {
                            count++;
                        } else {
                            count = MAX_TRIES;
                            IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                        } 
                    }
                }
            } else if(operation == 'delete') {
                try {
                    Database.DeleteResult result = Database.delete(record);
                } catch(DMLException de) {
                    IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                }
            } else if(operation == 'upsert') {
                Integer count = 0;
                while(count < MAX_TRIES) {
                    try {
                        Database.UpsertResult result = Database.upsert(record);
                        break;
                    } catch(DMLException de) {
                        if(de.getMessage().contains(UNABLE_TO_LOCK_ROW)) {
                            count++;
                        } else {
                            count = MAX_TRIES;
                            IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                        }
                    }
                }
            }
        }
    }
    
    
    /* Generic DML method which inserts,update,delete and upserts the records */
    public static LIST<Account> GenericListDMLOperationAccountRecords(LIST<SObject> recordLIST, String operation) {
        Database.SaveResult[] result;
        if(!recordLIST.isEmpty()) {
            if(operation == 'insert') {
                try {
                    result = Database.insert(recordLIST);
                } catch(DMLException de) {
                    IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                }
            }  
        }
        return recordLIST;
    }
    
     /* Generic DML method which inserts,update,delete and upserts the records */
    public static LIST<Database.SaveResult> GenericListDMLOperationWithReturn(LIST<SObject> recordLIST, String operation) {
        Database.SaveResult[] result;
        if(!recordLIST.isEmpty()) {
            if(operation == 'insert') {
                try {
                    result = Database.insert(recordLIST);
                } catch(DMLException de) {
                    IFv2_ExceptionUtilitiesController.exceptionHandler(de);
                }
            }  
        }
        
        return result;
    }
}