force-app/main/default/objects/Account/fields/IFv2_ContentType__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error Logs</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Time Data Amendment</fullName>
            </value>
            <value>
                <fullName>OT Application Details</fullName>
            </value>
            <value>
                <fullName>Leave Cancellation</fullName>
            </value>
            <value>
                <fullName>Leave Details</fullName>
            </value>
            <value>
                <fullName>China MAE After Split</fullName>
            </value>
            <value>
                <fullName>China MAE Before Split</fullName>
            </value>
            <value>
                <fullName>China MAE Combine</fullName>
            </value>
            <value>
                <fullName>China MAE Scrap</fullName>
            </value>
            <value>
                <fullName>China MAE Lost</fullName>
            </value>
            <value>
                <fullName>China MAE Transfer</fullName>
            </value>
            <value>
                <fullName>Approval History</fullName>
            </value>
            <value>
                <fullName>Sample ContentType Relatedlist_R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_LegacyActualApprover__c.field-meta.xml
<CustomField>
    <fullName>IFv2_LegacyActualApprover__c</fullName>
    <label>Actual Approver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Workflow__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Workflow__c</fullName>
    <description>The workflow name of the Request object</description>
    <label>Workflow</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/IFv2_AdminOnly__c.object-meta.xml
<CustomObject>
    <description>Only to be used for the System Admin</description>
    <label>InsightFlow 2.0 Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InsightFlow 2.0 Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Active checkbox which holds the Out of Office settngs</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/ProcessInstanceWorkItemId__c.field-meta.xml
<CustomField>
    <fullName>ProcessInstanceWorkItemId__c</fullName>
    <label>ProcessInstance WorkItem Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InsightFlow_2_0_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/WorkflowName__c.field-meta.xml
<CustomField>
    <fullName>WorkflowName__c</fullName>
    <description>Holds Workflow Name</description>
    <label>Workflow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/IFv2_Workflow__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Details of all the Workflows</description>
    <label>Workflow</label>
</CustomObject>

force-app/main/default/objects/IFv2_Workflow__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to activate/deactivate a workflow</description>
    <inlineHelpText>Select the checkbox if you want the workflow to be active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>The name of the Workflow</description>
    <inlineHelpText>Enter the name of the Workflow</inlineHelpText>
    <label>Workflow</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_HomePageRequestsOverviewTest.cls
/*******************************************************************************************************
* 
* @ Name    :   IFv2_HomePageRequestsOverviewTest
* @ Purpose :   Test class for HomeScreen
* @ Author  :   Madhura Vani
* @ Class   :   IFv2_HomePageRequestsOverview
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   31-03-2019      |  madhuravani.b@absyz.com      |  1.0          |  Initial Version
*
*******************************************************************************************************/
@isTest
public class IFv2_HomePageRequestsOverviewTest {
    public static IFv2_AdminOnly__c objAdmin; //holds Insightflow Records
    public static User objUser; //holds Users
    public static LIST<IFv2_Request__c> lstRequests; //Holds Requests
    public static IFv2_Workflow__c objWorkflow; //holds workflows
    
    /** Inserting the testdata **/
    @testsetup static void createTestData() {
        objUser = IFv2_testDataUtility.createUser();
        insert objUser;
        
        lstRequests = IFv2_testDataUtility.createRequest();
        lstRequests[0].Workflow__c = 'eSignature';
        lstRequests[0].Status__c = 'Submitted';
        insert lstRequests[0];
        
        objWorkflow = IFv2_testDataUtility.createWorkflowCustomSetting();    
        insert objWorkflow;
        
        objAdmin = new IFv2_AdminOnly__c();
        objAdmin.Active__c = true;
        objAdmin.WorkflowName__c = 'eSignature';
        objAdmin.User__c = objUser.Id;
        objAdmin.ProcessInstanceWorkItemId__c = lstRequests[0].id;
        insert objAdmin;
    }
    
    /**Calling the methods by satisfying Conditions **/
    static testmethod void homeMethods() {
        objAdmin = [SELECT id,name,WorkflowName__c,Active__c,User__c,User__r.Id,User__r.Username
                    FROM IFv2_AdminOnly__c 
                    LIMIT 1];
        System.assertEquals(true, objAdmin != Null);
        
        lstRequests= [SELECT id,name from IFv2_Request__c limit 1];
        System.assertEquals(true, !lstRequests.isEmpty()); 
        
        objWorkflow = [SELECT id from IFv2_Workflow__c limit 1];
        System.assertEquals(true, objWorkflow != Null); 
        
        //Calling Approval Process
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(lstRequests[0].Id);
        req1.setSubmitterId(UserInfo.getUserId()); 
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        IFv2_HomePageRequestsOverviewController.getSectionMetadata();
        IFv2_HomePageRequestsOverviewController.getRequests();
        IFv2_HomePageRequestsOverviewController.getOutOfOfficeData();
        //BacktoOffice JSON
        string strBackToOffice = '{"Name":\"'+objAdmin.WorkflowName__c+'\","Id":\"'+objAdmin.Id+'\","userId":\"'+objAdmin.User__r.Id+'\","UserName":\"'+objAdmin.User__r.Username+'\"}';
        IFv2_HomePageRequestsOverviewController.DisableOutOfOfficeSettings(strBackToOffice);
        IFv2_HomePageRequestsOverviewController.saveOutOfOfficeSettings(objAdmin.id,objAdmin.Active__c,objAdmin.WorkflowName__c,objAdmin.User__r.Id);
        IFv2_HomePageRequestsOverviewController.UpdateOutOfOfficeBackToOffice(false);
        Test.startTest();
        IFv2_HomePageRequestsOverviewController.saveOutOfOfficeSettings('',objAdmin.Active__c,'All',objAdmin.User__r.Id);
        Test.stopTest();
    }
    
    /** Null Conditions **/
    static testmethod void adminRecordNew() {
        objAdmin = [SELECT id,name,WorkflowName__c,Active__c,User__c,User__r.Id,User__r.Username
                    FROM IFv2_AdminOnly__c 
                    LIMIT 1];
        System.assertEquals(true, objAdmin != Null);
        
        IFv2_AdminOnly__c objEmptyAdmin = new IFv2_AdminOnly__c();
        string strBackToOffice = '{"Name":\"'+objEmptyAdmin.WorkflowName__c+'\","Id":\"'+objEmptyAdmin.Id+'\","userId":\"'+objAdmin.User__r.Id+'\","UserName":\"'+objAdmin.User__r.Username+'\"}';
        IFv2_HomePageRequestsOverviewController.DisableOutOfOfficeSettings(strBackToOffice);
        IFv2_HomePageRequestsOverviewController.saveOutOfOfficeSettings('',objAdmin.Active__c,objEmptyAdmin.WorkflowName__c,objAdmin.User__r.Id);
        IFv2_HomePageRequestsOverviewController.UpdateOutOfOfficeBackToOffice(false);
    }
    
    /* Creating test records for migrated old records */
    public static void migrationRecords(){
        
        lstRequests = IFv2_testDataUtility.createRequest();
        lstRequests[0].Workflow__c = 'eSignature';
        lstRequests[0].Status__c = 'Submitted';
        insert lstRequests[0];
        system.assertEquals('Submitted', lstRequests[0].Status__c);
        
        id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Request Items').getRecordTypeId();
        
        Account testAccount = new Account();
        testAccount.Name = 'Approval History test records';
        testAccount.IFv2_ContentType__c = 'Approval History';
        testAccount.IFv2_Request__c = lstRequests[0].Id;
        testAccount.IFv2_LegacyActualApprover__c = userInfo.getUserId();
        testAccount.RecordTypeId = accountRecordTypeId;
        insert testAccount;
        system.debug(testAccount);
        IFv2_HomePageRequestsOverviewController.getRequestApprovedByMe();
        
    }
}