force-app/main/default/objects/Account/fields/IFv2_ContentType__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error Logs</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Time Data Amendment</fullName>
            </value>
            <value>
                <fullName>OT Application Details</fullName>
            </value>
            <value>
                <fullName>Leave Cancellation</fullName>
            </value>
            <value>
                <fullName>Leave Details</fullName>
            </value>
            <value>
                <fullName>China MAE After Split</fullName>
            </value>
            <value>
                <fullName>China MAE Before Split</fullName>
            </value>
            <value>
                <fullName>China MAE Combine</fullName>
            </value>
            <value>
                <fullName>China MAE Scrap</fullName>
            </value>
            <value>
                <fullName>China MAE Lost</fullName>
            </value>
            <value>
                <fullName>China MAE Transfer</fullName>
            </value>
            <value>
                <fullName>Approval History</fullName>
            </value>
            <value>
                <fullName>Sample ContentType Relatedlist_R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/IFv2_UpdateAccountNameBatch.cls
/*******************************************************************************************************
* 
* @ Name 			: IFv2_UpdateAccountType
* @ Purpose 		: Class to update account name with INF.
* @ Author			: Vivek
* @ Test Class Name : IFv2_UpdateAccountTypeTest
*
*   Date        |  Developer Name                 |  Version      |  Changes
* ======================================================================================================
*   01-07-2019  |  vivek.kothalanka@absyz.com     |  1.0          |  Initial Version

*******************************************************************************************************/
global class IFv2_UpdateAccountNameBatch implements Database.Batchable<sObject>  {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,Name,ownerId,IFv2_Request__r.Name,RecordType.name,IFv2_ContentType__c FROM ACCOUNT WHERE (recordtype.Name = \'Request Extension\' OR recordtype.Name = \'Customer\' OR recordtype.Name =\'Request Items\') and ownerId !=\''+Label.CLIFv20022 +'\' and NAME like \'%INF%\'';
        system.debug('query'+query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, list<Account> AccountUpdateList) {
        try{
            system.debug('AccountUpdateList'+AccountUpdateList);
            IFv2_UpdateAccountName.UpdateAccountName(AccountUpdateList);            
        } catch(Exception e){
            IFv2_ExceptionUtilitiesController.exceptionHandler(e);
        }
    }
    global void finish(Database.BatchableContext bc) {
        
    }
}