force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>AccountRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Approver for the Workflow Request</inlineHelpText>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/RequestExtension1__c.field-meta.xml
<CustomField>
    <fullName>RequestExtension1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is look up for Request Extension1-APAC.</description>
    <label>Request Extension1</label>
    <referenceTo>IFv2_RequestExtension1__c</referenceTo>
    <relationshipLabel>Request Extension1</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/RequestExtension2__c.field-meta.xml
<CustomField>
    <fullName>RequestExtension2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is look up for Request Extension2-EMEA</description>
    <label>Request Extension2</label>
    <referenceTo>IFv2_RequestExtension2__c</referenceTo>
    <relationshipLabel>Request Extension2</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/RequestExtension3__c.field-meta.xml
<CustomField>
    <fullName>RequestExtension3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is look up for Request Extension3 - NALA</description>
    <label>Request Extension3</label>
    <referenceTo>IFv2_RequestExtension3__c</referenceTo>
    <relationshipLabel>Request Extension3</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/IFv2_RequestExtension1__c.object-meta.xml
<CustomObject>
    <description>Hold the requests of the APAC region</description>
    <label>Request Extension 1 - APAC</label>
    <nameField>
        <label>Request Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Extension 1 - APAC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_RequestExtension2__c/IFv2_RequestExtension2__c.object-meta.xml
<CustomObject>
    <description>Hold the requests of the EMEA region</description>
    <label>Request Extension 2 - EMEA</label>
    <nameField>
        <label>Request Extension 2 - EMEA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Extension 2 - EMEA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_RequestExtension3__c/IFv2_RequestExtension3__c.object-meta.xml
<CustomObject>
    <description>Hold the requests of the NALA region.</description>
    <label>Request Extension 3 - NALA</label>
    <nameField>
        <label>Request Extension 3 - NALA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Extension 3 - NALA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/IFv2_UserTriggerTest.cls
/*******************************************************************************************************
* 
* @ Name    :   IFv2_UserTriggerTest
* @ Purpose :   Test data for Trigger handler User trigger methods
* @ Author  :   Elsa Shaju
* @ Class	: 	IFv2_TriggerHandler
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   29-10-2019      |  elsa.shaju@absyz.com         |  1.0          |  Initial Version
*
*******************************************************************************************************/
@isTest
public class IFv2_UserTriggerTest {

    	public static list<IFv2_Request__c> lstRequest ;
    	public static Account objAcc;
    	public static User objUser; 
        public static User objUserDelegate;
    
    public static testmethod void testMethod1() {
	
        test.startTest();
        objUser = IFv2_testDataUtility.createUser();
        objUser.Username = 'abc@deltest.com';
        insert objUser;
        objUserDelegate = IFv2_testDataUtility.createUser();
        objUserDelegate.Username = 'abcd@deltest.com';
        insert objUserDelegate;
        
        objAcc = IFv2_testDataUtility.createAccount();
        objAcc.Name = 'Travelling';
        insert objAcc;
        
        lstRequest = IFv2_testDataUtility.createRequest();
        lstRequest[0].Workflow__c = 'eSignature';
        lstRequest[0].Status__c = 'Draft';
        lstRequest[0].Approver1__c = objUser.id; 
        insert lstRequest ;
        
        IFv2_RequestExtension1__c extension1 = new IFv2_RequestExtension1__c();
        insert extension1;
        IFv2_RequestExtension2__c extension2 = new IFv2_RequestExtension2__c();
        insert extension2;
        IFv2_RequestExtension3__c extension3 = new IFv2_RequestExtension3__c();
        insert extension3;
        
        lstRequest[0].Account__c = objAcc.Id;
        lstRequest[0].RequestExtension1__c = extension1.Id;
        lstRequest[0].RequestExtension2__c = extension2.Id;
        lstRequest[0].RequestExtension3__c = extension3.Id;
        update lstRequest[0];
        
        System.assertEquals(true, lstRequest[0].Workflow__c == 'eSignature');
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(lstRequest[0].Id);
        req1.setSubmitterId(UserInfo.getUserId()); 
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        objUser.DelegatedApproverId = objUserDelegate.Id;
        update objUser;
		
        test.stopTest();
    }
}