force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Workflow__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Workflow__c</fullName>
    <description>The workflow name of the Request object</description>
    <label>Workflow</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/ArchivalStatus__c.field-meta.xml
<CustomField>
    <fullName>ArchivalStatus__c</fullName>
    <label>Archival Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>considerforzipping</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>ToBeDeleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ChallanTypeofGatePass__c.field-meta.xml
<CustomField>
    <fullName>ChallanTypeofGatePass__c</fullName>
    <description>Type of Gate Pass</description>
    <inlineHelpText>Enter the type of gate pass for the challan</inlineHelpText>
    <label>Challan - Type of Gate Pass</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Returnable</fullName>
            </value>
            <value>
                <fullName>Non - Returnable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ContentversionIds__c.field-meta.xml
<CustomField>
    <fullName>ContentversionIds__c</fullName>
    <label>ContentversionIds</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/OldRequest__c.field-meta.xml
<CustomField>
    <fullName>OldRequest__c</fullName>
    <label>Old Request</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ParentRequest__c.field-meta.xml
<CustomField>
    <fullName>ParentRequest__c</fullName>
    <label>Parent Request</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Scan__c.field-meta.xml
<CustomField>
    <fullName>Scan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the ICO request to its related SCAN record</description>
    <label>Scan</label>
    <referenceTo>Scan__c</referenceTo>
    <relationshipLabel>ICO Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/WorkflowId__c.field-meta.xml
<CustomField>
    <fullName>WorkflowId__c</fullName>
    <description>Id of workflow custom setting record</description>
    <label>Workflow Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/IFv2_Workflow__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Details of all the Workflows</description>
    <label>Workflow</label>
</CustomObject>

force-app/main/default/objects/IFv2_Workflow__c/fields/ArchivingAfterDays__c.field-meta.xml
<CustomField>
    <fullName>ArchivingAfterDays__c</fullName>
    <defaultValue>180</defaultValue>
    <inlineHelpText>Enter the number of days after which the record should be archived</inlineHelpText>
    <label>Archiving After (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>The name of the Workflow</description>
    <inlineHelpText>Enter the name of the Workflow</inlineHelpText>
    <label>Workflow</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_ArchivalBatch.cls
/*******************************************************************************************************
* 
* @ Name : IFv2_ArchivalBatch
* @ Purpose : Class that collects Requests which are Approved,Rejected,Cancelled and meet Archival condition(currentdate=lastmodifieddate+workflowarchivaldate)
* @ Author: Naga Sai
* @ Test Class Name : IFV2_ArchivalBatchTest
*
*   Date        |  Developer Name                       |  Version      |  Changes
* ======================================================================================================
*   13-03-2019  |  nagasai.chalamalasetti@absyz.com     |  1.0          |  Initial Version

********************************************************************************************************
/** Each reuqest record which satisfies the condition of archival and also records which are archived will be queried **/
global class IFv2_ArchivalBatch implements Database.Batchable<sObject>, Database.Stateful{
    global String WorkflowId;
    global String Workflowname;
    global Datetime approxLastModifiedDate;
    //The logic is to have a set which stores processed workflow ids and use that set as a filter to query
    global  SET<Id> workflowids = new SET<Id>();
    global IFv2_ArchivalBatch(String WorkflowId,String Workflowname, Datetime approxLastModifiedDate,SET<Id> workflowidSet){
        workflowids=workflowidSet;
        this.WorkflowId = WorkflowId;
        this.Workflowname = Workflowname;
        this.approxLastModifiedDate = approxLastModifiedDate;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        LIST<String> requestStatusValues = label.CLIFv20197.split(','); 
        String requestquery = 'SELECT Id, Name, ArchivalStatus__c, ContentversionIds__c,OldRequest__c, Workflow__c, LastModifiedDate, ParentRequest__c, ChallanTypeofGatePass__c,Scan__r.ArchivingDate__c,Scan__r.ArchivingStatus__c	,Scan__c ' +
            'FROM IFv2_Request__c ' +
            'WHERE ArchivalStatus__c != \'considerforzipping\' ' +
            'AND (WorkflowId__c=:WorkflowId OR(WorkflowId__c=Null AND Workflow__c=:Workflowname)) '+
            'AND (lastmodifieddate<=:approxLastModifiedDate OR ArchivalStatus__c = \'Archived\' OR ArchivalStatus__c = \'fail\' OR OldRequest__c!=Null) '+
            'AND (Status__c in:requestStatusValues) ';
        return Database.getQueryLocator(requestquery);		
    }
    
    //1. Archival date of the respective request is queried using its workflow name
    //2. checks whether the record satisfies the archival conditon based on last modified date
    //3. if the record is already archived, then an archival log is created in admin only object with record type archival logs, and once they are created ,respective request is deleted
    //4. if not archived and if it satisfies archival conditon, then xml and pdf of the request are created using IFv2_ParseRequestToXMLANDPDF class.
    //5. Finally all the contentversions are queried and are filled into a ContentversionIds__c field of request and status is changed to 'considerforzipping'. 
    
    global void execute(Database.BatchableContext BC, LIST<IFv2_Request__c> RequestLIST) {
        try{
            if(RequestLIST.size()==1){
                if(RequestLIST[0].OldRequest__c==Null || RequestLIST[0].ArchivalStatus__c == 'Archived'){
                    if(RequestLIST[0].Scan__c==Null){
                        IFv2_ArchivalHandler.executeArchivalLogic(RequestLIST,Workflowname);
                    }
                }
                else{
                    system.debug('entering');
                    LIST<Account> oldApprovals = [select id,createddate from Account where IFv2_Request__c=:RequestLIST[0].id order by createddate desc limit 1];
                    if(oldApprovals.size()>0 && oldApprovals[0].createddate <=approxLastModifiedDate ){
                        IFv2_ArchivalHandler.executeArchivalLogic(RequestLIST,Workflowname);
                    }
                }
            }
        }
        catch(Exception e){
            IFv2_ExceptionUtilitiesController.exceptionHandler(e);
        }
        
    }
    
    /* Finish method */
    global void finish(Database.BatchableContext BC) {
        //The logic is to have a set which stores processed workflow ids and use that set as a filter to query
        LIST<IFv2_Workflow__c> workflows = [SELECT Id, Workflow__c , ArchivingAfterDays__c FROM IFv2_Workflow__c  where id not in:workflowids  limit 1];
        for(IFv2_Workflow__c workflow:workflows){
            workflowids.add(workflow.id);
            //calculating approximate last modfied date using archival date on workflow and checking that this variable
            //should be equal or greater than lastmodifieddate on request record**/
            Datetime Todaysdate = datetime.now();
            if(workflow.ArchivingAfterDays__c!=Null){
                Datetime ApproxLastModifiedDate = Todaysdate.adddays(-(integer)workflow.ArchivingAfterDays__c);
                IFV2_ArchivalBatch archivalBatch = new IFV2_ArchivalBatch(workflow.id,workflow.Workflow__c ,ApproxLastModifiedDate,workflowids);
                //Batch size should be one  
                database.executebatch(archivalBatch,1);
            }
            
        }
    }
}