force-app/main/default/objects/Account/fields/IFv2_DocumentItem__c.field-meta.xml
<CustomField>
    <fullName>IFv2_DocumentItem__c</fullName>
    <inlineHelpText>SAP Document Item in Invoice Document</inlineHelpText>
    <label>Document Item</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>IFv2_FiscalYear__c</fullName>
    <description>SAP Fiscal Year.</description>
    <inlineHelpText>SAP Fiscal Year</inlineHelpText>
    <label>Fiscal Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>IFv2_InvoiceNumber__c</fullName>
    <description>Invoice number (FI document number).</description>
    <inlineHelpText>Invoice number (FI document number)</inlineHelpText>
    <label>Invoice Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_SalesforceID__c.field-meta.xml
<CustomField>
    <fullName>IFv2_SalesforceID__c</fullName>
    <description>Used in APM Workflows</description>
    <label>Salesforce ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_SAPUPDATERESULT__c.field-meta.xml
<CustomField>
    <fullName>IFv2_SAPUPDATERESULT__c</fullName>
    <label>SAP UPDATE RESULT</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>IFv2_SequenceNumber__c</fullName>
    <description>This is used in APM workflows, for sending status of request.</description>
    <label>Sequence Number</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_WorkflowNumber__c.field-meta.xml
<CustomField>
    <fullName>IFv2_WorkflowNumber__c</fullName>
    <description>Used in APM Workflows</description>
    <inlineHelpText>SAP APM Workflow number</inlineHelpText>
    <label>Workflow Number</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>AccountRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>71F0</fullName>
            </value>
            <value>
                <fullName>70A0</fullName>
            </value>
            <value>
                <fullName>70B0</fullName>
            </value>
            <value>
                <fullName>70D0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>Used for SCAN records in APM workflows</description>
    <inlineHelpText>The SAP company code</inlineHelpText>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Scan__c.field-meta.xml
<CustomField>
    <fullName>Scan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the ICO request to its related SCAN record</description>
    <label>Scan</label>
    <referenceTo>Scan__c</referenceTo>
    <relationshipLabel>ICO Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scan__c/fields/IFv2_SAPStatus__c.field-meta.xml
<CustomField>
    <fullName>IFv2_SAPStatus__c</fullName>
    <description>Used to display the SAP call status of the SCAN record</description>
    <label>SAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IFv2_SAPCalloutHandlerTest.cls
/*******************************************************************************************************
* 
* @ Name    	: IFv2_SAPCalloutHandlerTest
* @ Purpose 	: Test class for IFv2_SAPCalloutHandler
* @ Author  	: Pradeep Chary
* @	Class Name	: IFv2_SAPCalloutHandler
*
*   Date        |  Developer Name                       |  Version      |  Changes
* ======================================================================================================
*   14-11-2018  |  pradeep.chary@absyz.com(yv)			|  1.0          |  Initial Version

*******************************************************************************************************/

@isTest
public class IFv2_SAPCalloutHandlerTest {
    
    public static LIST<Scan__c> scanRecordList;
    public static LIST<IFv2_Request__c> requestRecordLIST;
    public static Attachment pdfAttachment;
    public static Attachment xmlAttachment;
    public static User objUser;
    
    @testsetup static void createTestData() {
        
        scanRecordList = IFv2_testDataUtility.createScanRecord(2);
        insert scanRecordList;
        System.assertEquals(true, !scanRecordList.isEmpty());
        
        pdfAttachment = IFv2_testDataUtility.insertPdfAttachment(scanRecordList[0].Id);
        insert pdfAttachment;
        pdfAttachment.Name = 'Test pdf';
        update pdfAttachment;
        System.assertEquals(true, pdfAttachment.Name == 'Test pdf');
        
        xmlAttachment = IFv2_testDataUtility.insertXmlAttachment(scanRecordList[0].Id);
        insert xmlAttachment;
        System.assertEquals(true, xmlAttachment!=Null);
        
        requestRecordLIST = IFv2_testDataUtility.createRequestForScan(scanRecordList[0].Id);
        System.assertEquals(true, !requestRecordLIST.isEmpty());
        
        /*commented for cleaning up of Insightflow 1.0 components
* LIST<WF_Request__c> IFv1requestLIST = new LIST<WF_Request__c>();
LIST<WF_Request__c> IFv1requestLIST2 = new LIST<WF_Request__c>(); */
        MAP<Id,String> scanIdNameMap = new MAP<Id,String>();
        
        for(Scan__c scan : [SELECT Id, Name FROM Scan__c WHERE Id =: scanRecordList[0].Id]) {
            scanIdNameMap.put(scan.Id, scan.Name);
        }
    }
    
    public static TestMethod void calloutMethod() {
        Test.startTest();
        LIST<Scan__c> testScanLIST = [SELECT Id,Name,IFv2_SAPStatus__c, SAP_Response__c 
                                      FROM Scan__c];
        System.assertEquals(true, !testScanLIST.isEmpty());
        
        IFv2_SAPCalloutHandler.httpSapCall(testScanLIST[0].Id, testScanLIST[0].Name);
        Test.stopTest();
    }
    
    public static TestMethod void calloutMethodIFv1() {
        Test.startTest();
        LIST<Scan__c> testScanLIST = [SELECT Id,Name,IFv2_SAPStatus__c, SAP_Response__c 
                                      FROM Scan__c];
        System.assertEquals(true, !testScanLIST.isEmpty());
        /*commented for cleaning up of Insightflow 1.0 components
SG_WF_SAP_COM_STRUC_HANDLER.httpSapCall(testScanLIST[0].Id, testScanLIST[0].Name);
*/
        Test.stopTest();
    }
    
    public static TestMethod void scanTriggerMethod() {
        Test.startTest();
        LIST<Scan__c> testScanLIST = [SELECT Id,Name,IFv2_SAPStatus__c, SAP_Response__c 
                                      FROM Scan__c];
        System.assertEquals(true, !testScanLIST.isEmpty());
        
        Scan__c scanToUpdate = testScanLIST[0];
        scanToUpdate.IFv2_SAPStatus__c = 'Draft';
        scanToUpdate.SAP_Response__c = Null;
        scanToUpdate.IsArchived__c = 'N';
        update scanToUpdate;
        System.assertEquals(true, scanToUpdate.IFv2_SAPStatus__c == 'Draft');
        System.assertEquals(true, scanToUpdate.SAP_Response__c == Null);
        Test.stopTest();
    }
    
    public static TestMethod void soapUpdateMethod() {
        Test.startTest();
        requestRecordLIST = [SELECT  Id, Status__c,Scan__c,Workflow__c,Account__r.IFv2_SAPUPDATERESULT__c,Account__r.IFv2_SequenceNumber__c, CompanyCode__c, Account__r.IFv2_InvoiceNumber__c, Account__r.IFv2_FiscalYear__c,
                             Account__r.IFv2_DocumentItem__c, Account__r.IFv2_SalesforceID__c,Account__r.IFv2_WorkflowNumber__c
                             FROM IFv2_Request__c];
        System.assertEquals(true, !requestRecordLIST.isEmpty());
        
        LIST<Id> requestIdList = new LIST<Id>();
        for(IFv2_Request__c req: requestRecordLIST) {
            requestIdList.add(req.Id);
        }
        IFv2_SAPCalloutHandler.soapUpdateSapStatus(requestIdList);
        Test.stopTest();
    }
    
    public static TestMethod void soapUpdateMethodIFv1() {
        
        Test.startTest();
        scanRecordList = IFv2_testDataUtility.createScanRecord(2);
        insert scanRecordList;
        LIST<Scan__c> scanrecord = [SELECT Id, Name FROM Scan__c WHERE Id = :scanRecordList[0].Id];
        /*commented for cleaning up of Insightflow 1.0 components   
* WF_Request__c request = new WF_Request__c();
request.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = '39 AP Monitor workflow-6'].Id;
request.Workflow_Number__c = '06';
request.Status__c = 'Draft';
request.Salesforce_Id__c = scanrecord[0].Name;
insert request; */
        
        IFv2_testDataUtility.insertPdfAttachment(scanrecord[0].id);
        IFv2_testDataUtility.insertXmlAttachment(scanrecord[0].id);
        /*commented for cleaning up of Insightflow 1.0 components
* request.Status__c = 'Submitted';
update request;
LIST<WF_Request__c> IFv1requestLIST = [SELECT  Id, Status__c, Company_Code__c, Invoice_Number__c, Fiscal_Year__c,
Document_Item__c, APM_Workflow_Name__c, Salesforce_Id__c, Sequence_Number__c,Workflow_Number__c
FROM WF_Request__c WHERE Id = :request.Id]; 

System.assertEquals(true, !IFv1requestLIST.isEmpty());

LIST<Id> requestIdList = new LIST<Id>();
for(WF_Request__c req : IFv1requestLIST) {
requestIdList.add(req.Id);
}
SG_WF_SAP_COM_STRUC_HANDLER.soapUpdateSapStatus(requestIdList); */
        Test.stopTest();
    }
}