force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>AccountRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/DisplayApprovalHistory__c.field-meta.xml
<CustomField>
    <fullName>DisplayApprovalHistory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True - for displaying both Old and New Approval History Related List
False - only new Approval History</description>
    <inlineHelpText>True - for displaying both Old and New Approval History Related List
False - only new Approval History</inlineHelpText>
    <label>Display Approval History</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/OldRequest__c.field-meta.xml
<CustomField>
    <fullName>OldRequest__c</fullName>
    <label>Old Request</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>This is used for Reporting in eSignature request object.</description>
    <inlineHelpText>Enter the version of the request.</inlineHelpText>
    <label>Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IFv2_ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to handle Validation Rules from firing</description>
    <label>By Pass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IFv2_RelatedListsControllerTest.cls
/*******************************************************************************************************
* 
* @ Name        :   IFv2_RelatedListsControllerTest
* @ Purpose     :   Test class for generic related list
* @ Author      :   Madhura Vani
* @ Class Name  :   IFv2_RelatedListsController
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   20-11-2018      |  madhuravani.b@absyz.com      |  1.0          |  Initial Version
*
*******************************************************************************************************/
@isTest
public class IFv2_RelatedListsControllerTest {
    
    public static list<IFv2_Request__c> lstsObject ;
    public static user objUser;
    @testsetup static void createTestData() {
        //inserting Request
        objUser = IFv2_testDataUtility.createUser();
        objUser.IFv2_ByPassValidation__c = true;
        insert objUser;
        System.assertEquals(true, objUser.IFv2_ByPassValidation__c == true);
        
        System.runAs(objUser)
        {
            //inserting Request
            lstsObject = IFv2_testDataUtility.createRequest();
            insert lstsObject ;
        }
        objUser.IFv2_ByPassValidation__c = false;
        update objUser;
        System.assertEquals(true, objUser.IFv2_ByPassValidation__c == false);
    }
    
    public static testmethod void relatedListData(){
        test.startTest();
        lstsObject = [select id,name,Status__c from IFv2_Request__c];
        lstsObject[0].OldRequest__c = null;
        update lstsObject[0];
        IFv2_RelatedListsController.fetchRelatedList(lstsObject[0].Id, 'ProcessInstance');
        IFv2_RelatedListsController.completeRelatedList(lstsObject[0].Id, 'ProcessInstance');
        System.assertEquals(lstsObject[0].Status__c, 'Draft');
        test.stopTest();
    }
    
    public static testmethod void relatedListData1(){
        test.startTest();
        /*commented for cleaning up of Insightflow 1.0 components 
WF_Request__c obj1 = new WF_Request__c();
obj1.Description_Identification__c = 'test';
obj1.Version__c = '1.0';
obj1.Short_description__c = 'abc';
obj1.Release_date__c = system.today()+1;
try{
insert obj1;
}catch (Dmlexception e){
system.debug('lead update failed: '+e);
}
System.assertNotEquals(null, obj1);
IFv2_Request__c reqRecord = [select id,name,Status__c from IFv2_Request__c limit 1];
reqRecord.OldRequest__c = obj1.Id;
reqRecord.DisplayApprovalHistory__c = true;
update reqRecord;
IFv2_RelatedListsController.fetchRelatedList(reqRecord.Id, 'OldRequestApprovals');
//System.assertEquals(lstsObject[0].Status__c, 'Draft');
*/
        test.stopTest();
    }
    
    public static testmethod void relatedListData2(){
        test.startTest();
        lstsObject = [select id,name,Status__c from IFv2_Request__c];
        System.assertEquals(true, lstsObject != Null);
        try{
            IFv2_RelatedListsController.fetchRelatedList(lstsObject[0].Id, 'test');
        }catch (TypeException ee) {
            System.assertEquals(
                'Procedure is only valid for System.DmlException and System.MailException',
                ee.getMessage()
            );
        }
        test.stopTest();
    }
    
    public static testmethod void relatedListDataTest(){
        test.startTest();
        Account testAccount = new Account();
        testAccount.name = 'test';
        insert testAccount;
        IFv2_Request__c obj1 = new IFv2_Request__c();
        obj1.Status__c = 'Draft';
        obj1.Workflow__c = 'eSignature';
        obj1.Account__c = testAccount.Id;
        insert obj1;
        try{
            insert obj1;
        }catch (Dmlexception e){
            system.debug('lead update failed: '+e);
        }
        System.assertNotEquals(null, obj1);
        IFv2_Request__c reqRecord = [select id,name,Status__c from IFv2_Request__c limit 1];
        reqRecord.OldRequest__c = obj1.Id;
        reqRecord.DisplayApprovalHistory__c = true;
        update reqRecord;
        IFv2_RelatedListsController.fetchRelatedList(reqRecord.Id, 'OldRequestApprovals');
        //System.assertEquals(lstsObject[0].Status__c, 'Draft');

        test.stopTest();
    }
    
}