force-app/main/default/objects/Account/fields/IFv2_ContainmentAction2__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ContainmentAction2__c</fullName>
    <description>For Concession workflow in InsightFlow 2.0</description>
    <label>Containment Action 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_ContainmentAction3__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ContainmentAction3__c</fullName>
    <label>Containment Action 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_ContainmentAction4__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ContainmentAction4__c</fullName>
    <label>Containment Action 4</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_ContainmentAction5__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ContainmentAction5__c</fullName>
    <label>Containment Action 5</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_CustomerNo__c.field-meta.xml
<CustomField>
    <fullName>IFv2_CustomerNo__c</fullName>
    <description>Used in Concession Workflow</description>
    <label>Customer No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Escalatetomanagementlevel__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Escalatetomanagementlevel__c</fullName>
    <description>Used in Concession Workflow</description>
    <inlineHelpText>The second and further concessions with the same root cause must be escalated to the leading management level.</inlineHelpText>
    <label>Escalate to management level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Furtherprocessing__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Furtherprocessing__c</fullName>
    <description>Used in Concession Workflow</description>
    <inlineHelpText>Maximum Characters Allowed - 132</inlineHelpText>
    <label>Further processing</label>
    <length>132</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Plant__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Plant__c</fullName>
    <label>Plant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_SupplierNo__c.field-meta.xml
<CustomField>
    <fullName>IFv2_SupplierNo__c</fullName>
    <description>Used in Concession Workflow</description>
    <label>Supplier No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>AccountRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Approver for the Workflow Request</inlineHelpText>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/CategoryCodeDescription__c.field-meta.xml
<CustomField>
    <fullName>CategoryCodeDescription__c</fullName>
    <description>Used in Concession Workflow</description>
    <label>Category Code Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>QS-RM001-0010 Concession inhouse production (product)</fullName>
            </value>
            <value>
                <fullName>QS-RM001-0020 Concession inhouse production (process)</fullName>
            </value>
            <value>
                <fullName>QS-RM001-0030 Concession inhouse production (product and customer)</fullName>
            </value>
            <value>
                <fullName>QS-RM001-0040 Concession inhouse production (process and customer)</fullName>
            </value>
            <value>
                <fullName>QS-RM002-0030 Concession external procurement (supplier, SOP)</fullName>
            </value>
            <value>
                <fullName>QS-RM002-0040 Concession external procurement (supplier, repet. manufact.)</fullName>
            </value>
            <value>
                <fullName>QS-RM003-0050 Concession external procurement (internal, SOP)</fullName>
            </value>
            <value>
                <fullName>QS-RM003-0060 Concession external procurement (internal, repet. manufact.)</fullName>
            </value>
            <value>
                <fullName>QS-RM004-0010 pres-series conc.(in-house production) pre-series conc. (product)</fullName>
            </value>
            <value>
                <fullName>QS-RM004-0020 pres-series conc.(in-house production) pre-series conc. (process)</fullName>
            </value>
            <value>
                <fullName>QS-RM004-0030 pres-series conc.(in-house production) pre-series conc. (product and customer)</fullName>
            </value>
            <value>
                <fullName>QS-RM004-0040 pres-series conc.(in-house production) pre-series conc. (process and customer)</fullName>
            </value>
            <value>
                <fullName>QS-RM005-0070 pres-series conc.(external procurement) pre-series conc. (resp: internal)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ConcessionDescription__c.field-meta.xml
<CustomField>
    <fullName>ConcessionDescription__c</fullName>
    <description>Used in Concession workflow.</description>
    <inlineHelpText>Maximum Characters Allowed - 132</inlineHelpText>
    <label>Description</label>
    <length>132</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Full8Dreportnecessary__c.field-meta.xml
<CustomField>
    <fullName>Full8Dreportnecessary__c</fullName>
    <description>Used in Concession Workflow</description>
    <label>Full 8D report necessary?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/MaterialNo__c.field-meta.xml
<CustomField>
    <fullName>MaterialNo__c</fullName>
    <description>Used in Concession Workflow</description>
    <label>Material No</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <description>Used in Concession and MGP Workflow</description>
    <inlineHelpText>Please enter any remarks for this process</inlineHelpText>
    <label>Remarks</label>
    <length>132</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/SAPInstance__c.field-meta.xml
<CustomField>
    <fullName>SAPInstance__c</fullName>
    <description>Used in Concession Workflow</description>
    <label>SAP Instance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PSG</fullName>
            </value>
            <value>
                <fullName>PSI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/SupplierName__c.field-meta.xml
<CustomField>
    <fullName>SupplierName__c</fullName>
    <description>Used in indirect Purchasing Approval</description>
    <label>Supplier/Customer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_ConcessionWorkflowHandlerTest.cls
/*******************************************************************************************************
* 
* @ Name    :   IFv2_ConcessionWorkflowHandlerTest
* @ Purpose :   Test data for IFv2_ConcessionWorkflowHandler
* @ Author  :   Kanchan
* @ Class	: 	IFv2_ConcessionWorkflowHandler
*
*   Date            |  Developer Name           |  Version      |  Changes
* ======================================================================================================
*   15-01-2019      |  Kanchan.b@absyz.com      |  1.0          |  Initial Version
*
*******************************************************************************************************/
@isTest(SeeAllData=true)
public class IFv2_ConcessionWorkflowHandlerTest {
    
    @isTest
    static void testCall(){
        /*commented for cleaning up of Insightflow 1.0 components 
Test.setMock(WebServiceMock.class, new SG_WF_WS_Sap_Con_CreateNotif_Mock());
*/
        Profile p =[SELECT ID FROM Profile Where Name='System Administrator'];
        User u = new user();
        u.alias = 'alias';
        u.LastName = 'lastName';
        u.Username = 'test@testingfsagdgdsbggfbsajkdf.com';
        u.Email = 'test@seg-automotive.com';
        u.TimeZoneSidKey = 'Europe/Berlin';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ProfileId = p.Id;
        u.Department = '123';
        insert u;
        
        
        IFv2_request__c req = new IFv2_request__c();
        req.Workflow__c='Concession';
        req.Status__c = 'Draft';
        
        req.Approver1__c=u.id;
        req.CategoryCodeDescription__c='QS-RM001-0010 Concession inhouse production (product)';
        req.MaterialNo__c='123';
        req.SupplierName__c='123';
        req.Full8Dreportnecessary__c='No';
        req.SAPInstance__c='PSI';
        req.Remarks__c='Remark';
        req.ConcessionDescription__c='concession desc';
        insert req;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(req.id);
        req1.setSubmitterId(u.Id); 
        req1.setSkipEntryCriteria(true);
        Approval.ProcessResult result = Approval.process(req1);
        
        
        Account acc= new Account();
        acc.IFv2_Request__c=req.Id;
        acc.IFv2_Plant__c='3123123123123123123';
        acc.Name='test Class';
        acc.IFv2_SupplierNo__c='123';
        acc.IFv2_CustomerNo__c='88';
        acc.IFv2_Furtherprocessing__c='123123123123332';
        acc.IFv2_Escalatetomanagementlevel__c='YES';
        acc.IFv2_ContainmentAction2__c='Action';
        acc.IFv2_ContainmentAction3__c='Action';
        acc.IFv2_ContainmentAction4__c='Action';
        acc.IFv2_ContainmentAction5__c='Action';
        insert acc;
        
        req.Account__c=acc.id;
        update req;
        
        
        List<String> reqList = new List<String>();
        reqList.add(req.Id);
        Map<String, String> httpHeaders = new Map<String,String>();
        httpHeaders.put('TEST', 'TEST');
        
        Test.startTest();
        IFv2_ConcessionWorkflowHandler.createNotificationWrapper(reqList, httpHeaders);
        List<IFv2_request__c> reqLess = [SELECT Id FROM IFv2_request__c LIMIT 1];
        System.assertEquals(true, reqLess.size()>0);
        Test.stopTest();
    }
    
    @isTest
    static void testCallTwo(){
        /*commented for cleaning up of Insightflow 1.0 components 
Test.setMock(WebServiceMock.class, new SG_WF_WS_Sap_Con_CreateNotif_Mock());
*/
        
        Profile p =[SELECT ID FROM Profile Where Name='System Administrator'];
        User u = new user();
        u.alias = 'alias';
        u.LastName = 'lastName';
        u.Username = 'test@testingfsagdgdsbggfbsajkdf.com';
        u.Email = 'test@seg-automotive.com';
        u.TimeZoneSidKey = 'Europe/Berlin';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ProfileId = p.Id;
        u.Department = '123';
        insert u;
        
        IFv2_request__c req = new IFv2_request__c();
        req.Workflow__c='Concession';
        req.Status__c = 'Draft';
        
        req.Approver1__c=u.id;
        req.CategoryCodeDescription__c='QS-RM001-0010 Concession inhouse production (product)';
        req.MaterialNo__c='123';
        req.SupplierName__c='123';
        req.Full8Dreportnecessary__c='Yes';
        req.Remarks__c='Remark';
        req.ConcessionDescription__c='concession desc';
        insert req;
        
        List<String> reqList = new List<String>();
        reqList.add(req.Id);
        Map<String, String> httpHeaders = new Map<String,String>();
        httpHeaders.put('TEST', 'TEST');
        
        Test.startTest();
        IFv2_ConcessionWorkflowHandler.createNotificationWrapper(reqList, httpHeaders);
        List<IFv2_request__c> reqLess = [SELECT Id FROM IFv2_request__c LIMIT 1];
        System.assertEquals(true, reqLess.size()>0);
        Test.stopTest();
        
    }
    
}