force-app/main/default/objects/Account/fields/IFv2_ChinaMAE__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ChinaMAE__c</fullName>
    <label>China MAE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_ContentType__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error Logs</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Time Data Amendment</fullName>
            </value>
            <value>
                <fullName>OT Application Details</fullName>
            </value>
            <value>
                <fullName>Leave Cancellation</fullName>
            </value>
            <value>
                <fullName>Leave Details</fullName>
            </value>
            <value>
                <fullName>China MAE After Split</fullName>
            </value>
            <value>
                <fullName>China MAE Before Split</fullName>
            </value>
            <value>
                <fullName>China MAE Combine</fullName>
            </value>
            <value>
                <fullName>China MAE Scrap</fullName>
            </value>
            <value>
                <fullName>China MAE Lost</fullName>
            </value>
            <value>
                <fullName>China MAE Transfer</fullName>
            </value>
            <value>
                <fullName>Approval History</fullName>
            </value>
            <value>
                <fullName>Sample ContentType Relatedlist_R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_FromDate__c.field-meta.xml
<CustomField>
    <fullName>IFv2_FromDate__c</fullName>
    <description>Used in China Leave and Overtime</description>
    <inlineHelpText>Input is mandatory</inlineHelpText>
    <label>From Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_LegacyActualApprover__c.field-meta.xml
<CustomField>
    <fullName>IFv2_LegacyActualApprover__c</fullName>
    <label>Actual Approver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_LegacyAssignedTo__c.field-meta.xml
<CustomField>
    <fullName>IFv2_LegacyAssignedTo__c</fullName>
    <label>Assigned To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_LegacyComments__c.field-meta.xml
<CustomField>
    <fullName>IFv2_LegacyComments__c</fullName>
    <description>Old Request Approval Comments</description>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_LegacyStatus__c.field-meta.xml
<CustomField>
    <fullName>IFv2_LegacyStatus__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Legacysubmitter__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Legacysubmitter__c</fullName>
    <label>Submitter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_PersonnelNo__c.field-meta.xml
<CustomField>
    <fullName>IFv2_PersonnelNo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to all Employees (Used in employee related list)</description>
    <inlineHelpText>Please select the Employee</inlineHelpText>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Request__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the IFv2_Request object</description>
    <label>Request Name</label>
    <referenceTo>IFv2_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ShortDescription__c</fullName>
    <description>This is used provide description.</description>
    <label>Short Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_StepName__c.field-meta.xml
<CustomField>
    <fullName>IFv2_StepName__c</fullName>
    <description>Stores the step name of the Approval Process</description>
    <label>Step Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IFv2_Workflow__c.field-meta.xml
<CustomField>
    <fullName>IFv2_Workflow__c</fullName>
    <description>The workflow name of the Request object</description>
    <label>Workflow</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>AccountRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/OldRequest__c.field-meta.xml
<CustomField>
    <fullName>OldRequest__c</fullName>
    <label>Old Request</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/PlannedDate__c.field-meta.xml
<CustomField>
    <fullName>PlannedDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Used in China Applications</description>
    <inlineHelpText>Please Choose a planned date</inlineHelpText>
    <label>Planned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/RequestExtension1__c.field-meta.xml
<CustomField>
    <fullName>RequestExtension1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is look up for Request Extension1-APAC.</description>
    <label>Request Extension1</label>
    <referenceTo>IFv2_RequestExtension1__c</referenceTo>
    <relationshipLabel>Request Extension1</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/TotalPlannedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalPlannedDuration__c</fullName>
    <description>This is used in China Travel workflow, for showing roll up summary of planned duration.</description>
    <inlineHelpText>Displays total planned duration days.</inlineHelpText>
    <label>Total Planned Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/IFv2_RequestExtension1__c.object-meta.xml
<CustomObject>
    <description>Hold the requests of the APAC region</description>
    <label>Request Extension 1 - APAC</label>
    <nameField>
        <label>Request Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Extension 1 - APAC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_RequestExtension1__c/fields/PlannedEndDateTime__c.field-meta.xml
<CustomField>
    <fullName>PlannedEndDateTime__c</fullName>
    <description>Used in China Applications</description>
    <label>Planned End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/fields/PlannedStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>PlannedStartDateTime__c</fullName>
    <description>Used in China Travel Application</description>
    <label>Planned Start Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IFv2_RequestExtension1__c/fields/TotalPlannedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalPlannedDuration__c</fullName>
    <description>This is used in China Travel workflow, for showing roll up summary of planned duration.</description>
    <inlineHelpText>Displays total planned duration days.</inlineHelpText>
    <label>Total Planned Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/IFv2_Section__mdt.object-meta.xml
<CustomObject>
    <description>To store different sections to be displayed on the request detail page and workflow detail page in InsightFlow application version 2.0</description>
    <label>Section</label>
    <pluralLabel>Section</pluralLabel>
</CustomObject>

force-app/main/default/objects/IFv2_Section__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Describes the name of the Section.</description>
    <inlineHelpText>Please enter the Name of the section to be displayed on the layout</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/fields/ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please check to make the section read only</inlineHelpText>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/fields/SectionNumber__c.field-meta.xml
<CustomField>
    <fullName>SectionNumber__c</fullName>
    <description>Used to provide order number for displaying the section in request detail page.</description>
    <inlineHelpText>Please enter the position of the section</inlineHelpText>
    <label>Section Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Describes whether the section is for Workflow details page or Request details page or Related list.</description>
    <inlineHelpText>Workflow details - For Workflow Detail section
Request details - For Request Detail section
Related lists - For Related List section</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Workflow details</fullName>
                <default>true</default>
                <label>Workflow details</label>
            </value>
            <value>
                <fullName>Request details</fullName>
            </value>
            <value>
                <fullName>Related list</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Used to provide the field set name in in request detail page or set of fields to be displayed in workflow detail page.</description>
    <inlineHelpText>Workflow details - Enter field API names
Request details - Enter the fieldset API name
Related lists - Enter the fieldset API name
To enter the API names of the fields to be displayed. If API names exceeds 255 characters enter custom label name.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Section__mdt/fields/Workflows__c.field-meta.xml
<CustomField>
    <fullName>Workflows__c</fullName>
    <description>Describes to which workflow record this section belongs to.</description>
    <inlineHelpText>Please select the workflow to which the section is related to</inlineHelpText>
    <label>Workflows</label>
    <referenceTo>IFv2_Workflows__mdt</referenceTo>
    <relationshipLabel>Section</relationshipLabel>
    <relationshipName>Section</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IFv2_Workflow__c/IFv2_Workflow__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Details of all the Workflows</description>
    <label>Workflow</label>
</CustomObject>

force-app/main/default/objects/IFv2_Workflow__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>The name of the Workflow</description>
    <inlineHelpText>Enter the name of the Workflow</inlineHelpText>
    <label>Workflow</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IFv2_ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to handle Validation Rules from firing</description>
    <label>By Pass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IFv2_PrintableViewControllerTest.cls
/*******************************************************************************************************
* 
* @ Name 			: IFv2_PrintableViewControllerTest
* @ Purpose 		: Test class for IFv2_PrintableViewController
* @ Author			: Prasad Vivek
* @ Class Name      : IFv2_PrintableViewController 
*
*   Date            |  Developer Name                 |  Version     |  Changes
* ======================================================================================================
*   02-05-2019      |  vivek.kothalanka@absyz.com	  |  1.1         |  Initial version
*
*******************************************************************************************************/
@isTest
public class IFv2_PrintableViewControllerTest {
    
    public static list<IFv2_Request__c> lstsObject = new list<IFv2_Request__c>();
    public static IFv2_Workflow__c lstWF;
    public static contact objCon;
    public static Account objAcc;
    public static User objUser;
    @testsetup static void createTestData() {
        objAcc = IFv2_testDataUtility.createAccount();
        objAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        insert objAcc;
        
        objCon = IFv2_testDataUtility.createContact(objAcc);
        insert objCon;
        
        objUser = IFv2_testDataUtility.createUser();
        objUser.IFv2_ByPassValidation__c = true;
        insert objUser;
        
        system.runAs(objUser)
        {
            lstWF =   IFv2_testDataUtility.createWorkflowCustomSetting();
            IFv2_Request__c req = new IFv2_Request__c();
            req.Workflow__c = 'Esignature';
            req.Status__c ='Draft';
            lstsObject.add(req);
            insert lstsObject ;
        }
        
        objUser.IFv2_ByPassValidation__c = false;
        update objUser; 
    }
    
    @TestVisible private static IFv2_Section__mdt getRecordMetadata(){
        IFv2_Section__mdt RecordMetadata = [
            select id,Name__c,ReadOnly__c, SectionNumber__c, Type__c, Workflows__c, Value__c
            from IFv2_Section__mdt limit 1
        ];
        
        return RecordMetadata;
    }
    
    public static TestMethod void redirectToPrintableViewMethod() {
        IFv2_PrintableViewController controllerInstance = new IFv2_PrintableViewController();
        LIST<FeedComment> FeedCommentLIST = new LIST<FeedComment>();
        
        
        LIST<IFv2_Request__c> requestObjectLIST = [SELECT Id 
                                                   FROM IFv2_Request__c LIMIT 1];
        system.assertEquals(1,requestObjectLIST.size());
        
        FeedItem feedItemRecord = new FeedItem();
        feedItemRecord.ParentId = userInfo.getUserId();
        feedItemRecord.Body = 'Test';
        feedItemRecord.Type = 'ContentPost';
        if(!requestObjectLIST.isEmpty()){
            feedItemRecord.ParentId =  requestObjectLIST[0].Id; 
        }
        
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'Test data';
        contentVersion.PathOnClient = 'test.jpg';
        contentVersion.VersionData = Blob.valueOf('Test Content data');
        contentVersion.IsMajorVersion = true;
        insert contentVersion;
        Attachment file = new Attachment();
        file.Name='test';
        file.body=     Blob.valueOf('Test Content data');
        file.ParentId=requestObjectLIST[0].Id;
        insert file;
        LIST<ContentDocument> ContentDocumentLIST = [SELECT Id, Title, LatestPublishedVersionId 
                                                     FROM ContentDocument];
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        if(requestObjectLIST[0] != NULL)
            cdl.LinkedEntityId = requestObjectLIST[0].Id;
        if(ContentDocumentLIST[0] != NULL)
            cdl.ContentDocumentId = ContentDocumentLIST[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        Account accountRecord = new Account();
        accountRecord.Name = 'Approval History' ;
        accountRecord.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Request Items').getRecordTypeId();
        accountRecord.IFv2_ContentType__c = 'Approval History';
        // accountRecord.IFv2_Legacysubmitter__c = objUser.id;
        //accountRecord.IFv2_LegacyActualApprover__c = objUser.id;
        //accountRecord.IFv2_LegacyAssignedTo__c = objUser.id;
        accountRecord.IFv2_LegacyStatus__c = 'Recalled';
        
        
        accountRecord.IFv2_LegacyComments__c = 'test';
        accountRecord.IFv2_Request__c =requestObjectLIST[0].id ;
        
        accountRecord.IFv2_StepName__c = 'Approval Request Submitted';
        
        
        insert accountRecord;
        FeedComment feed=new FeedComment();
        feed.CommentBody='<p>we must introspect on the reasons for declined COQs.</p>';
        feed.CommentType='TextComment';
        feed.createddate=system.today();
        feed.CreatedBy=objUser;
       // feed.FeedItemId= feedItemRecord.Id;
        //insert feed;
        FeedCommentLIST.add(feed);
        IFv2_printableviewController.chatterparentId =  requestObjectLIST[0].Id;
        IFv2_printableviewController.getchatterRelatedList();
        controllerInstance.getOldApprovalRelatedList();
        String returnValue = IFv2_printableviewController.getChatterComments(FeedCommentLIST);
        IFv2_printableviewController.getContentVersions();
        
    }
    
    
    public static testmethod void printableviewtest(){
        test.startTest();
        
        Account testAccount = new Account();
        testAccount.name = 'test';
        testAccount.CreatedDate=system.today();
        testAccount.IFv2_FromDate__c=system.today();
        //testAccount.IFv2_ShortDescription__c = 'Test Description';
        insert testAccount;
        IFv2_Request__c r = new IFv2_Request__c();
        r.Status__c = 'Draft';
        r.Workflow__c = 'eSignature';
        r.Account__c = testAccount.Id;
        //r.LastReferencedDate = system.today();
       // r.PlannedDate__c = '2021-03-16';
        r.CreatedDate=system.today();
        insert r;
        Account testAccount1 = new Account();
        testAccount1.name = 'test2';
        testAccount1.IFv2_ContentType__c='Employee';
        testAccount1.recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Request Items').getRecordTypeId();
        testAccount1.IFv2_Request__c=r.id;
        
        insert testAccount1;
        Approval.ProcessSubmitRequest requestitem = new Approval.ProcessSubmitRequest();
        //set the target objcet as request 
        requestitem.setObjectId(r.id);
        //pass user id which will be coming from approval process
        requestitem.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        //set comments 
        requestitem.setComments('Submitted for approval. Please approve.');
        //submit the approval process
        Approval.ProcessResult result = Approval.process(requestitem);
        system.assertEquals('Pending', (String)result.getInstanceStatus());
        ApexPages.currentPage().getParameters().put('id',r.id);
        IFv2_PrintableViewController objPrintableView = new IFv2_PrintableViewController();
        
        IFv2_Request__c req = IFv2_PrintableViewController.getRecord('IFv2_Request__c',r.id);
        system.assertEquals(req.Id,r.id);
        objPrintableView.getApprovalRelatedList();
        
        IFv2_RequestExtension1__c extension = new IFv2_RequestExtension1__c();
        extension.TotalPlannedDuration__c = 6;
        extension.PlannedEndDateTime__c =  datetime.newInstance(2019, 9, 17, 12, 30, 0);
        extension.PlannedStartDateTime__c =  datetime.newInstance(2019, 9, 16, 12, 30, 0);
        insert extension;
        r.Workflow__c = 'China Training Application';
        r.RequestExtension1__c = extension.Id;
        update r;
        IFv2_Request__c req1 = IFv2_PrintableViewController.getRecord('IFv2_Request__c',r.id);
        system.assertEquals(req1.Id,r.id);
        objPrintableView.getApprovalRelatedList();
        
        test.stopTest();
        
    }
    
    public static testmethod void printableviewtestM1(){
        test.startTest();
        
        Account testAccount = new Account();
        testAccount.name = 'test';
        testAccount.CreatedDate=system.today();
        testAccount.IFv2_FromDate__c=system.today();
        //testAccount.IFv2_ShortDescription__c = 'Test Description';
        insert testAccount;
        IFv2_RequestExtension1__c extension = new IFv2_RequestExtension1__c();
        extension.TotalPlannedDuration__c = 6;
        extension.PlannedEndDateTime__c =  datetime.newInstance(2019, 9, 17, 12, 30, 0);
        extension.PlannedStartDateTime__c =  datetime.newInstance(2019, 9, 16, 12, 30, 0);
        insert extension;
        IFv2_Request__c r = new IFv2_Request__c();
        r.Status__c = 'Draft';
        r.Workflow__c = 'China Training Application';
        r.RequestExtension1__c = extension.Id;
        r.Account__c = testAccount.Id;
        //r.LastReferencedDate = system.today();
       // r.PlannedDate__c = '2021-03-16';
        r.CreatedDate=system.today();
        insert r;
        Account testAccount1 = new Account();
        testAccount1.name = 'test2';
        testAccount1.IFv2_ContentType__c='Employee';
        testAccount1.recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Request Items').getRecordTypeId();
        testAccount1.IFv2_Request__c=r.id;
        
        insert testAccount1;
        Approval.ProcessSubmitRequest requestitem = new Approval.ProcessSubmitRequest();
        //set the target objcet as request 
        requestitem.setObjectId(r.id);
        //pass user id which will be coming from approval process
        requestitem.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        //set comments 
        requestitem.setComments('Submitted for approval. Please approve.');
        //submit the approval process
        Approval.ProcessResult result = Approval.process(requestitem);
       // system.assertEquals('Pending', (String)result.getInstanceStatus());
        ApexPages.currentPage().getParameters().put('id',r.id);
        IFv2_PrintableViewController objPrintableView = new IFv2_PrintableViewController();
        
        IFv2_Request__c req = IFv2_PrintableViewController.getRecord('IFv2_Request__c',r.id);
        system.assertEquals(req.Id,r.id);
        objPrintableView.getApprovalRelatedList();
        
        
       // r.Workflow__c = 'China Training Application';
        //r.RequestExtension1__c = extension.Id;
        //update r;
       // IFv2_Request__c req1 = IFv2_PrintableViewController.getRecord('IFv2_Request__c',r.id);
       // system.assertEquals(req1.Id,r.id);
       // objPrintableView.getApprovalRelatedList();
        
        test.stopTest();
        
    }
    
    
    public static testmethod void printableviewtestMethod2(){
        
        test.startTest();
        Account testAccount = new Account();
        testAccount.name = 'test';
        insert testAccount;
        
        RecordType objRecordType = [SELECT id,Name FROM RecordType WHERE SobjectType = 'Account' and Name = 'Request Items' Limit 1]; 
        objUser = [select id,name from User limit 1];
        /*commented for cleaning up of Insightflow 1.0 components
Workflow__c oldWorkflow = IFv2_testDataUtility.createOldWorkflow();
insert oldWorkflow;
Request_EMEA__c oldRequest = IFv2_testDataUtility.createRequestEMEA(oldWorkflow, objUser);
insert oldRequest; */
        IFv2_Request__c objReq = [select id,name,oldrequest__c,status__c from IFv2_Request__c limit 1];
        // objReq.OldRequest__c = oldRequest.Id;
        objReq.Account__c = testAccount.Id;
        update objReq;
        objAcc = [select id,name,IFv2_ContentType__c,IFv2_ChinaMAE__c,IFv2_PersonnelNo__c,IFv2_LegacyAssignedTo__c,IFv2_LegacyActualApprover__c,IFv2_Legacysubmitter__c from Account limit 1];
        
        Account accountForContact = new Account();
        accountForContact.Name = 'Account for Contact';
        accountForContact.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        insert accountForContact;
        objCon = IFv2_testDataUtility.createContact(accountForContact);
        insert objCon;
        
        objAcc.IFv2_ContentType__c = 'Approval History';
        objAcc.RecordtypeId = objRecordType.id;
        objAcc.IFv2_Request__c = objReq.id;
        objAcc.IFv2_ChinaMAE__c = 'test';
        objAcc.IFv2_PersonnelNo__c = objCon.id;
        
        objAcc.IFv2_LegacyAssignedTo__c = string.valueOf(objUser.Id);
        objAcc.IFv2_LegacyActualApprover__c = string.valueOf(objUser.Id);
        objAcc.IFv2_Legacysubmitter__c = string.valueOf(objUser.Id); 
        
        update objAcc;
        
        system.assertEquals(objAcc.IFv2_LegacyAssignedTo__c,string.valueOf(objUser.Id));
        
        Approval.ProcessSubmitRequest requestitem = new Approval.ProcessSubmitRequest();
        //set the target objcet as request 
        requestitem.setObjectId(objReq.id);
        //pass user id which will be coming from approval process
        requestitem.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        //set comments 
        requestitem.setComments('Submitted for approval. Please approve.');
        //submit the approval process
        Approval.ProcessResult result = Approval.process(requestitem);
        system.assertEquals('Pending', result.getInstanceStatus());
        apexpages.StandardController sc = new ApexPages.StandardController(objReq);
        
        IFv2_PrintableViewController v=new IFv2_PrintableViewController(sc);
        v.getOldApprovalRelatedList();
        test.stopTest();
    }
    
    public static testmethod void printableviewtestMethod3(){
        
        test.startTest();
        
        Account testAccount = new Account();
        testAccount.name = 'test';
        insert testAccount;
        IFv2_Request__c r = new IFv2_Request__c();
        r.Status__c = 'Draft';
        r.Workflow__c = 'eSignature';
        r.Account__c = testAccount.Id;
        insert r;
        
        // Create an approval request instance
        Approval.ProcessSubmitRequest requestitem = new Approval.ProcessSubmitRequest();
        //set the target objcet as request 
        requestitem.setObjectId(r.id);
        //pass user id which will be coming from approval process
        requestitem.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        //set comments 
        requestitem.setComments('Submitted for approval. Please approve.');
        //submit the approval process
        Approval.ProcessResult result = Approval.process(requestitem);
        apexpages.StandardController sc = new ApexPages.StandardController(r);
        
        IFv2_PrintableViewController v=new IFv2_PrintableViewController(sc);
        // v.getApprovalRelatedList();
        IFv2_RelatedListsController.RelatedList Approvalhistory = IFv2_RelatedListsController.completeRelatedList(r.id,'ProcessInstance');
        system.assertEquals(label.CLIFv20035,Approvalhistory.columnLabels);
        test.stopTest();
        
    }
    
    public static testmethod void printableviewtest4(){
        test.startTest();
        
        Account testAccount = new Account();
        testAccount.name = 'test';
        insert testAccount;
        IFv2_Request__c r = new IFv2_Request__c();
        r.Status__c = 'Draft';
        r.Workflow__c = 'China Training Application';
        r.Account__c = testAccount.Id;
        insert r;
        Account testAccount1 = new Account();
        testAccount1.name = 'test2';
        testAccount1.IFv2_ContentType__c='Employee';
        testAccount1.recordtypeid=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Request Items').getRecordTypeId();
        testAccount1.IFv2_Request__c=r.id;
        
        insert testAccount1;
        Approval.ProcessSubmitRequest requestitem = new Approval.ProcessSubmitRequest();
        //set the target objcet as request 
        requestitem.setObjectId(r.id);
        //pass user id which will be coming from approval process
        requestitem.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        //set comments 
        requestitem.setComments('Submitted for approval. Please approve.');
        //submit the approval process
        Approval.ProcessResult result = Approval.process(requestitem);
        system.assertEquals('Rejected', result.getInstanceStatus());
        
        ApexPages.currentPage().getParameters().put('id',r.id);
        IFv2_PrintableViewController objPrintableView = new IFv2_PrintableViewController();
        
        IFv2_Request__c req = IFv2_PrintableViewController.getRecord('IFv2_Request__c',r.id);
        System.assertEquals(req.Id,r.id);
        objPrintableView.getApprovalRelatedList();
        test.stopTest();
    }
}