force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/OldRequest__c.field-meta.xml
<CustomField>
    <fullName>OldRequest__c</fullName>
    <label>Old Request</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <description>This field is used for reporting in eSignature request.</description>
    <inlineHelpText>Select the Release date.</inlineHelpText>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>This is used for Reporting in eSignature request object.</description>
    <inlineHelpText>Enter the version of the request.</inlineHelpText>
    <label>Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IFv2_ByPassValidation__c.field-meta.xml
<CustomField>
    <fullName>IFv2_ByPassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to handle Validation Rules from firing</description>
    <label>By Pass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IFv2_ThankYouForWaitingControllerTest.cls
/*******************************************************************************************************
* 
* @ Name    :   IFv2_ThankYouForWaitingControllerTest
* @ Purpose :   Test class for Thank you page to redirect to the current system
* @ Author  :   Madhura Vani 
* @ Class	:	IFv2_ThankYouForWaitingController
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   26-11-2018      |  madhuravani.b@absyz.com      |  1.0          |  Initial Version   
*******************************************************************************************************/
@isTest
public class IFv2_ThankYouForWaitingControllerTest {
    public static list<IFv2_Request__c> lstRequest ;
    public static User objUser;
    public static testmethod void ThankyouData(){
        
        objUser = IFv2_testDataUtility.createUser();
        objUser.IFv2_ByPassValidation__c = true;
        insert objUser;
        IFv2_Request__c objReq = new IFv2_Request__c(); 
        system.runAs(objUser)
        {
            objReq.Status__c = 'Draft' ;
            objReq.OldRequest__c = '123';
            insert objReq;
        }
        
        objUser.IFv2_ByPassValidation__c = false;
        update objUser; 
        
        Pagereference page = Page.IFv2_ThankYouForWaiting;
        
        Test.setCurrentPage(page);
        ApexPages.currentPage().getParameters().put('Id','123');
        
        IFv2_Request__Share chatterShare = new IFv2_Request__Share();
        chatterShare.ParentId = objReq.Id;
        chatterShare.UserOrGroupId = userinfo.getUserId();
        chatterShare.AccessLevel = 'read';
        chatterShare.RowCause = Schema.IFv2_Request__Share.RowCause.SharingRecordsWithChatter__c;
        insert chatterShare;
        
        IFv2_ThankYouForWaitingController obj = new IFv2_ThankYouForWaitingController();
        try{
            IFv2_ThankYouForWaitingController.redirectToActualRecord();
            obj.clickHme();
        } catch (TypeException ee) {
            System.assertEquals(
                'Procedure is only valid for System.DmlException and System.MailException',
                ee.getMessage()
            );
        }
    }
    
    public static testmethod void ThankyouData2(){
        
        IFv2_Request__c objReq = new IFv2_Request__c(); 
        objReq.Status__c = 'Draft' ;
        objReq.Workflow__c='eSignature';
        objReq.Version__c='test1';
        ObjReq.ReleaseDate__c=Date.newInstance(2019, 12, 20);
        insert objReq;
        
        
        lstRequest = [select id from IFv2_Request__c limit 1];
        system.assertEquals(1,lstRequest.size());
        System.debug('check id>>'+objReq.id);
        //  ApexPages.currentPage().getParameters().put('id',objReq.id);
        /* Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
app.setObjectId(objReq.id);
Approval.ProcessResult result = Approval.process(app);
*/
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(objReq.id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        Test.setCurrentPageReference(new PageReference('Page.IFv2_ThankYouForWaiting')); 
        System.currentPageReference().getParameters().put('id', objReq.id);
        
        IFv2_ThankYouForWaitingController obj = new IFv2_ThankYouForWaitingController();
        IFv2_ThankYouForWaitingController.recordId = objReq.id;
        IFv2_ThankYouForWaitingController.redirectToActualRecord();
    }
    /*commented for cleaning up of Insightflow 1.0 components
public static testmethod void ThankyouData3(){
WF_Request__c objReq = new WF_Request__c();
objReq.Status__c = 'Draft';
insert objReq;
system.assertEquals('Draft',objReq.Status__c);
ApexPages.currentPage().getParameters().put('id',objReq.id);
IFv2_ThankYouForWaitingController obj = new IFv2_ThankYouForWaitingController();
IFv2_ThankYouForWaitingController.redirectToActualRecord(); 
}

public static testmethod void ThankyouDataDelete(){
WF_Request__c objReq = new WF_Request__c();
objReq.Status__c = 'Draft';
insert objReq;
system.assertEquals('Draft',objReq.Status__c);
IFv2_ThankYouForWaitingController.redirectToActualRecord();
} */
}