force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Approver for the Workflow Request</inlineHelpText>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver3__c.field-meta.xml
<CustomField>
    <fullName>Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver4__c.field-meta.xml
<CustomField>
    <fullName>Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver5__c.field-meta.xml
<CustomField>
    <fullName>Approver5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Provide Approver 5 value.</description>
    <label>Approver 5</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Approver6__c.field-meta.xml
<CustomField>
    <fullName>Approver6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to provide Approver 6.</description>
    <label>Approver 6</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>71F0</fullName>
            </value>
            <value>
                <fullName>70A0</fullName>
            </value>
            <value>
                <fullName>70B0</fullName>
            </value>
            <value>
                <fullName>70D0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>Used for SCAN records in APM workflows</description>
    <inlineHelpText>The SAP company code</inlineHelpText>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_PendingApprovalReportTest.cls
/***************************************************************************************************************
* 
* @ Name 		:	IFv2_PendingApprovalReportTest
* @ Purpose 	: 	For sending report regarding ICO workflows
* @ Author		: 	Prasad Vivek
* @ Test class  :   IFv2_PendingApprovalReport
*
*   Date	        |  Developer Name               |  Version      |  Changes
* ==================================================================================================================
*   05-11-2018      |  vivek.kothalanka@absyz.com	|  1.1          | 	Initial version to send ICO workflows  
*
*******************************************************************************************************************/
@istest
public class IFv2_PendingApprovalReportTest {
    
  @testSetUp Public static  void testDataMethod() {
        
        user userRecord = IFv2_TestDataUtility.createSGStandardUser();
        userRecord.Username = 'testUsericomail@gmail.com';
        userRecord.Country = 'Germany';
        insert userRecord;
    }
    
    public static testmethod void testschedule() {
        
        Test.StartTest();
        
        User  UserRecord = [SELECT Id FROM user LIMIT 1];
        system.assertEquals(true, UserRecord!= NULL);
        list<IFv2_Request__c> requestLIST = new list<IFv2_Request__c>();
        list<IFv2_Request__c> testDataUtility = IFv2_TestDataUtility.createRequest();
        for(IFv2_Request__c request : testDataUtility) {
            request.Status__c = 'Submitted';
            request.CompanyCode__c = '9000';
            request.Approver1__c = userRecord.Id;
            request.Approver2__c = userRecord.Id;
            request.Approver3__c = userRecord.Id;
            request.Approver4__c = userRecord.Id;
            request.Approver5__c = userRecord.Id;
            request.Approver6__c = userRecord.Id;
            request.Workflow__c = 'ICO Workflow - 1';
            requestLIST.add(request);
        }
        insert requestLIST;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestLIST[0].Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req1.setProcessDefinitionNameOrId('IFv2_ICOWorkflowsCommon');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        All_Pending_Approval__c allPending = new All_Pending_Approval__c();
        allPending.Company_Code__c = '9000';
        allPending.Pex_Email1__c = 'testabsyz@gamil.com';
        allPending.Pex_Email2__c = 'testabsyz@gamil.com';
        allPending.Pex_Email3__c = 'testabsyz@gamil.com';
        allPending.Pex_Email4__c = 'testabsyz@gamil.com';
        allPending.Pex_Email5__c =	'testabsyz@gamil.com';
        allPending.Pex_Email6__c = 'testabsyz@gamil.com';
        allPending.Name ='Test';
        insert allPending;
        
        IFv2_PendingApprovalReport sh1 = new IFv2_PendingApprovalReport();      
        String sch = '0 0 23 * * ?';
        system.schedule('PendingApprovalReportPart2A', sch, sh1);
        IFv2_PendingApprovalReport_batch_mlb obj = new IFv2_PendingApprovalReport_batch_mlb();
        DataBase.executeBatch(obj);
        Test.stopTest();        
    } 
    
    public static testmethod void testscheduleMethod2() {
        
        Test.StartTest();
        
        User  UserRecord = [SELECT Id FROM user LIMIT 1];
        system.assertEquals(true, UserRecord!= NULL);
        list<IFv2_Request__c> requestLIST = new list<IFv2_Request__c>();
        list<IFv2_Request__c> testDataUtility = IFv2_TestDataUtility.createRequest();
        for(IFv2_Request__c request : testDataUtility) {
            request.Status__c = 'Submitted';
            request.CompanyCode__c = '71F0';
            request.Approver1__c = userRecord.Id;
            request.Approver2__c = userRecord.Id;
            request.Approver3__c = userRecord.Id;
            request.Approver4__c = userRecord.Id;
            request.Approver5__c = userRecord.Id;
            request.Approver6__c = userRecord.Id;
            request.Workflow__c = 'ICO Workflow - 1';
            requestLIST.add(request);
        }
        insert requestLIST;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestLIST[0].Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req1.setProcessDefinitionNameOrId('IFv2_ICOWorkflowsCommon');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        All_Pending_Approval__c allPending = new All_Pending_Approval__c();
        allPending.Company_Code__c = '71F0';
        allPending.Pex_Email1__c = 'testabsyz@gamil.com';
        allPending.Pex_Email2__c = 'testabsyz@gamil.com';
        allPending.Pex_Email3__c = 'testabsyz@gamil.com';
        allPending.Pex_Email4__c = 'testabsyz@gamil.com';
        allPending.Pex_Email5__c =	'testabsyz@gamil.com';
        allPending.Pex_Email6__c = 'testabsyz@gamil.com';
        allPending.Name ='Test';
        insert allPending;
        
        
        IFv2_PendingApprovalReport sh1 = new IFv2_PendingApprovalReport();      
        String sch = '0 0 23 * * ?';
        system.schedule('PendingApprovalReportPart2A', sch, sh1);
        IFv2_PendingApprovalReport_batch_mlb obj = new IFv2_PendingApprovalReport_batch_mlb();
        DataBase.executeBatch(obj);
        Test.stopTest();        
    }
    public static testmethod void testscheduleMethod3() {
        
        Test.StartTest();
        
        User  UserRecord = [SELECT Id FROM user LIMIT 1];
        system.assertEquals(true, UserRecord!= NULL);
        list<IFv2_Request__c> requestLIST = new list<IFv2_Request__c>();
        list<IFv2_Request__c> testDataUtility = IFv2_TestDataUtility.createRequest();
        for(IFv2_Request__c request : testDataUtility) {
            request.Status__c = 'Submitted';
            request.CompanyCode__c = '70A0';
            request.Approver1__c = userRecord.Id;
            request.Approver2__c = userRecord.Id;
            request.Approver3__c = userRecord.Id;
            request.Approver4__c = userRecord.Id;
            request.Approver5__c = userRecord.Id;
            request.Approver6__c = userRecord.Id;
            request.Workflow__c = 'ICO Workflow - 1';
            requestLIST.add(request);
        }
        insert requestLIST;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestLIST[0].Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req1.setProcessDefinitionNameOrId('IFv2_ICOWorkflowsCommon');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        All_Pending_Approval__c allPending = new All_Pending_Approval__c();
        allPending.Company_Code__c = '70A0';
        allPending.Pex_Email1__c = 'testabsyz@gamil.com';
        allPending.Pex_Email2__c = 'testabsyz@gamil.com';
        allPending.Pex_Email3__c = 'testabsyz@gamil.com';
        allPending.Pex_Email4__c = 'testabsyz@gamil.com';
        allPending.Pex_Email5__c =	'testabsyz@gamil.com';
        allPending.Pex_Email6__c = 'testabsyz@gamil.com';
        allPending.Name ='Test';
        insert allPending;
        
        
        IFv2_PendingApprovalReport sh1 = new IFv2_PendingApprovalReport();      
        String sch = '0 0 23 * * ?';
        system.schedule('PendingApprovalReportPart2A', sch, sh1);
        IFv2_PendingApprovalReport_batch_mlb obj = new IFv2_PendingApprovalReport_batch_mlb();
        DataBase.executeBatch(obj);
        Test.stopTest();        
    }
    public static testmethod void testscheduleMethod4() {
        
        Test.StartTest();
        
        User  UserRecord = [SELECT Id FROM user LIMIT 1];
        system.assertEquals(true, UserRecord!= NULL);
        list<IFv2_Request__c> requestLIST = new list<IFv2_Request__c>();
        list<IFv2_Request__c> testDataUtility = IFv2_TestDataUtility.createRequest();
        for(IFv2_Request__c request : testDataUtility) {
            request.Status__c = 'Submitted';
            request.CompanyCode__c = '70B0';
            request.Approver1__c = userRecord.Id;
            request.Approver2__c = userRecord.Id;
            request.Approver3__c = userRecord.Id;
            request.Approver4__c = userRecord.Id;
            request.Approver5__c = userRecord.Id;
            request.Approver6__c = userRecord.Id;
            request.Workflow__c = 'ICO Workflow - 1';
            requestLIST.add(request);
        }
        insert requestLIST;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestLIST[0].Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req1.setProcessDefinitionNameOrId('IFv2_ICOWorkflowsCommon');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        All_Pending_Approval__c allPending = new All_Pending_Approval__c();
        allPending.Company_Code__c = '70B0';
        allPending.Pex_Email1__c = 'testabsyz@gamil.com';
        allPending.Pex_Email2__c = 'testabsyz@gamil.com';
        allPending.Pex_Email3__c = 'testabsyz@gamil.com';
        allPending.Pex_Email4__c = 'testabsyz@gamil.com';
        allPending.Pex_Email5__c =	'testabsyz@gamil.com';
        allPending.Pex_Email6__c = 'testabsyz@gamil.com';
        allPending.Name ='Test';
        insert allPending;
        
        
        
        IFv2_PendingApprovalReport sh1 = new IFv2_PendingApprovalReport();      
        String sch = '0 0 23 * * ?';
        system.schedule('PendingApprovalReportPart2A', sch, sh1);
        IFv2_PendingApprovalReport_batch_mlb obj = new IFv2_PendingApprovalReport_batch_mlb();
        DataBase.executeBatch(obj);
        Test.stopTest();        
    }
    public static testmethod void testscheduleMethod5() {
        
        Test.StartTest();
        
        User  UserRecord = [SELECT Id FROM user LIMIT 1];
        system.assertEquals(true, UserRecord!= NULL);
        list<IFv2_Request__c> requestLIST = new list<IFv2_Request__c>();
        list<IFv2_Request__c> testDataUtility = IFv2_TestDataUtility.createRequest();
        for(IFv2_Request__c request : testDataUtility) {
            request.Status__c = 'Submitted';
            request.CompanyCode__c = '68C0';
            request.Approver1__c = userRecord.Id;
            request.Approver2__c = userRecord.Id;
            request.Approver3__c = userRecord.Id;
            request.Approver4__c = userRecord.Id;
            request.Approver5__c = userRecord.Id;
            request.Approver6__c = userRecord.Id;
            request.Workflow__c = 'ICO Workflow - 1';
            requestLIST.add(request);
        }
        insert requestLIST;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestLIST[0].Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req1.setProcessDefinitionNameOrId('IFv2_ICOWorkflowsCommon');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        All_Pending_Approval__c allPending = new All_Pending_Approval__c();
        allPending.Company_Code__c = '68C0';
        allPending.Pex_Email1__c = 'testabsyz@gamil.com';
        allPending.Pex_Email2__c = 'testabsyz@gamil.com';
        allPending.Pex_Email3__c = 'testabsyz@gamil.com';
        allPending.Pex_Email4__c = 'testabsyz@gamil.com';
        allPending.Pex_Email5__c =	'testabsyz@gamil.com';
        allPending.Pex_Email6__c = 'testabsyz@gamil.com';
        allPending.Name ='Test';
        insert allPending;
        
        
        IFv2_PendingApprovalReport sh1 = new IFv2_PendingApprovalReport();      
        String sch = '0 0 23 * * ?';
        system.schedule('PendingApprovalReportPart2A', sch, sh1);
        IFv2_PendingApprovalReport_batch_mlb obj = new IFv2_PendingApprovalReport_batch_mlb();
        DataBase.executeBatch(obj);
        Test.stopTest();        
    }
    
    public static testmethod void testscheduleMethod6() {
        
        Test.StartTest();
        
        User  UserRecord = [SELECT Id FROM user LIMIT 1];
        system.assertEquals(true, UserRecord!= NULL);
        list<IFv2_Request__c> requestLIST = new list<IFv2_Request__c>();
        list<IFv2_Request__c> testDataUtility = IFv2_TestDataUtility.createRequest();
        for(IFv2_Request__c request : testDataUtility) {
            request.Status__c = 'Submitted';
            request.CompanyCode__c = '69F0';
            request.Approver1__c = userRecord.Id;
            request.Approver2__c = userRecord.Id;
            request.Approver3__c = userRecord.Id;
            request.Approver4__c = userRecord.Id;
            request.Approver5__c = userRecord.Id;
            request.Approver6__c = userRecord.Id;
            request.Workflow__c = 'ICO Workflow - 1';
            requestLIST.add(request);
        }
        insert requestLIST;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestLIST[0].Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req1.setProcessDefinitionNameOrId('IFv2_ICOWorkflowsCommon');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        All_Pending_Approval__c allPending = new All_Pending_Approval__c();
        allPending.Company_Code__c = '69F0';
        allPending.Pex_Email1__c = 'testabsyz@gamil.com';
        allPending.Pex_Email2__c = 'testabsyz@gamil.com';
        allPending.Pex_Email3__c = 'testabsyz@gamil.com';
        allPending.Pex_Email4__c = 'testabsyz@gamil.com';
        allPending.Pex_Email5__c =	'testabsyz@gamil.com';
        allPending.Pex_Email6__c = 'testabsyz@gamil.com';
        allPending.Name ='Test';
        insert allPending;
        
        
        IFv2_PendingApprovalReport sh1 = new IFv2_PendingApprovalReport();      
        String sch = '0 0 23 * * ?';
        system.schedule('PendingApprovalReportPart2A', sch, sh1);
        IFv2_PendingApprovalReport_batch_mlb obj = new IFv2_PendingApprovalReport_batch_mlb();
        DataBase.executeBatch(obj);
        Test.stopTest();        
    }
}