force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Local_Expert_Id__c.field-meta.xml
<CustomField>
    <fullName>Local_Expert_Id__c</fullName>
    <label>Local Expert Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IFv2_LocalExpertDetailsTest.cls
/*******************************************************************************************************
* 
* @ Name    :   IFv2_LocalExpertDetailsTest
* @ Purpose :   Test class for IFv2_LocalExpertDetails.
* @ Author  :   external.debasmita.rawooth@seg-automotive.com
*
*   Date        |  Developer Name                      					|  Version       |  Changes
* ======================================================================================================
*   04-10-2019  |  external.debasmita.rawooth@seg-automotive.com        |  	1.0			 | Initial Version
*******************************************************************************************************/
@isTest(SeeAllData=true)
public class IFv2_LocalExpertDetailsTest {
    
    public static testmethod void testLocalExpert() {
        User user1 = [Select id,name from user Limit 1];
        IFv2_Request__c req = new IFv2_Request__c(); 
        req.Local_Expert_Id__c = user1.Id;
        req.Status__c = 'Draft';
        insert req;
        List<User> getUserList = IFv2_LocalExpertDetails.getLocalExpertDetails(req.Id);
    }
    
}