force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_GenerateChallanControllerTest.cls
/*******************************************************************************************************
* 
* @ Name    	:   IFv2_GenerateChallanControllerTest
* @ Purpose 	:   Test class for IFv2_GenerateChallanController
* @ Author  	:   Nagasai
* @ Class Name	:	IFv2_GenerateChallanController
*
*   Date        |  Developer Name                   	|  Version      |  Changes
* ======================================================================================================
*   21-05-2019  |  nagasai.chalamalasetti@absyz.com     |  1.0          |  Initial Version
*
*******************************************************************************************************/
@isTest
public class IFv2_GenerateChallanControllerTest {
    
    
    public static testmethod void getchallanHTML(){
        test.startTest();
        IFv2_Request__c r = new IFv2_Request__c();
        r.Status__c = 'Draft';
        r.Workflow__c = 'Material Gate Pass';
        insert r;
        system.assertEquals('Material Gate Pass',r.Workflow__c);
        PageReference pr = new PageReference('/apex/IFv2_GenerateChallanPage');
        pr.getParameters().put('id', r.Id);
        apexpages.StandardController sc = new ApexPages.StandardController(r);
        //leveragin the printableview controller for the XML purpose, this class returns map of field name and its value
        IFv2_GenerateChallanController v=new IFv2_GenerateChallanController(sc);
        IFv2_GenerateChallanController.requestid = r.id;
        IFv2_GenerateChallanController.getchallanHTML();
        test.stopTest();
    }
}