force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Parallel__c.field-meta.xml
<CustomField>
    <fullName>Parallel__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in General Approval Form</description>
    <label>Parallel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Scan__c.field-meta.xml
<CustomField>
    <fullName>Scan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the ICO request to its related SCAN record</description>
    <label>Scan</label>
    <referenceTo>Scan__c</referenceTo>
    <relationshipLabel>ICO Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used in General Approval Form</description>
    <label>Serial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_SummaryCmpControllerTest.cls
/*******************************************************************************************************
* 
* @ Name    :   IFv2_SummaryCmpControllerTest
* @ Purpose :   Test class for IFv2_SummaryCmpController
* @ Author  :   Pradeep Chary
* @ Class	: 	IFv2_SummaryCmpController
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   02-01-2018      |  pradeep.chary@absyz.com      |  1.0          |  Initial Version
*
*******************************************************************************************************/

@isTest
public class IFv2_SummaryCmpControllerTest {
    
    public static LIST<Scan__c> scanRecordList;
    public static LIST<IFv2_Request__c> requestRecordLIST;
    public static User objUser;
    
    public static TestMethod void fetchRelatedRequestsMethod() {
        scanRecordList = IFv2_testDataUtility.createScanRecord(2);
        insert scanRecordList;
        System.assertEquals(true, !scanRecordList.isEmpty());
        
        requestRecordLIST = IFv2_testDataUtility.createRequest();
        requestRecordLIST[0].Workflow__c = 'eSignature';
        requestRecordLIST[0].Parallel__c = true;
        requestRecordLIST[0].Serial__c = false;
        requestRecordLIST[0].Scan__c = scanRecordList[0].Id;
        insert requestRecordLIST;
        System.assertEquals(true, !requestRecordLIST.isEmpty());
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(requestRecordLIST[0].Id);
        req1.setSubmitterId(UserInfo.getUserId());
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req1.setProcessDefinitionNameOrId('IFv2_eSignature');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        IFv2_SummaryCmpController.fetchRelatedRequests(requestRecordLIST[0].Id, requestRecordLIST[0].Status__c);
        
    }
}