force-app/main/default/objects/IFv2_Request__c/IFv2_Request__c.object-meta.xml
<CustomObject>
    <description>Request Object to store all information for each request</description>
    <label>Request</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_Request__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Approver for the Workflow Request</inlineHelpText>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ChallanTypeofGatePass__c.field-meta.xml
<CustomField>
    <fullName>ChallanTypeofGatePass__c</fullName>
    <description>Type of Gate Pass</description>
    <inlineHelpText>Enter the type of gate pass for the challan</inlineHelpText>
    <label>Challan - Type of Gate Pass</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Returnable</fullName>
            </value>
            <value>
                <fullName>Non - Returnable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/DetailLink__c.field-meta.xml
<CustomField>
    <fullName>DetailLink__c</fullName>
    <formula>$User.IFv2_InstanceDomain__c+&apos;apex/IFv2_ThankYouForWaiting?Id=&apos;+Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DetailLink</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/DueDateofReturn__c.field-meta.xml
<CustomField>
    <fullName>DueDateofReturn__c</fullName>
    <label>Due Date of Return</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/ParentRequest__c.field-meta.xml
<CustomField>
    <fullName>ParentRequest__c</fullName>
    <label>Parent Request</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Request</description>
    <inlineHelpText>Describes the status of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Verify</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFv2_Request__c/fields/Workflow__c.field-meta.xml
<CustomField>
    <fullName>Workflow__c</fullName>
    <description>This field describes the workflow name of the request.</description>
    <inlineHelpText>Describes the workflow name of the request</inlineHelpText>
    <label>Workflow</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_MaterialBatch.cls
/*******************************************************************************************************
* 
* @ Name		:  IFv2_MaterialBatch
* @ Purpose		:  Batch class to send emails to applicant and Department Head if due date is crossed and materials are pending to be returned
* @ Author		:  Elsa Shaju
* @ Test Class  :  IFv2_MaterialBatchControllerTest
*
*   Date            |  Developer Name               |  Version      |  Changes
* ======================================================================================================
*   20-05-2019      |  elsa.shaju@absyz.com         |  1.0          |  Initial Version

*******************************************************************************************************/

public class IFv2_MaterialBatch implements Database.Batchable<Sobject>, Schedulable {
    public IFv2_MaterialBatch() {
        
    }
    /* Start Method for Batch Class*/
    public Database.QueryLocator start(Database.BatchableContext bc){
        String workflow = Label.CLIFv20200;
        String query = 'SELECT Id, Name,ParentRequest__c '+
            ' FROM IFv2_Request__c' + 
            ' WHERE (Workflow__c = \''+workflow +'\''+
            ' AND Status__c = \'Submitted\''+
            ' AND DueDateofReturn__c = Today'+
            ' AND ChallanTypeofGatePass__c = \'Returnable\')';
        return Database.getQueryLocator(query);
    }
    /*Execute method for Batch Class*/
    public void execute(Database.BatchableContext bc, LIST<IFv2_Request__c> requests){
        LIST<Messaging.SingleEmailMessage> allSingleEmailLIST = new LIST<Messaging.SingleEmailMessage>();
        set<String> parentReqSet = new set<String>();
        if(!requests.isEmpty()){
            for(IFv2_Request__c req: requests){
                parentReqSet.add(req.ParentRequest__c);
            }
        }
        String query = 'SELECT Id, Name, CreatedById, Approver1__c, DueDateofReturn__c,DetailLink__c, CreatedBy.Name, Approver1__r.Name, CreatedBy.Email, Approver1__r.Email '+
            ' FROM IFv2_Request__c' + 
            ' WHERE (Workflow__c = \''+Label.CLIFv20199 +'\''+
            ' AND Id IN :parentReqSet)';
        LIST<IFv2_Request__c> parentRequests = new LIST<IFv2_Request__c>();
        if(!parentReqSet.isEmpty()){
            parentRequests = Database.query(query);
        }
        //List to store single email messages
        LIST<Contact> contactLIST = [SELECT Id FROM Contact LIMIT 1];
        if(!parentRequests.isEmpty()) {
            for(IFv2_Request__c request : parentRequests) {
                if(request.CreatedBy.Email != null && request.Approver1__r.Email != null) {
                    String bodyApplicant = '<Html><body> Dear ' + request.CreatedBy.Name + ',<br/><br/>' +
                        'The materials for the below request <br/>' +
                        'Request : ' + '<a href="'+request.DetailLink__c+'">'+request.Name+'</a><br/>'+
                        'has been due for return on ' + request.DueDateofReturn__c +'<br/>' +
                        'Please consider this as a reminder <br/><br/><br/>'+
                        '___________________________________________<br/>'+
                        'Please do not reply to this automated mail.<br/>'+
                        '</body></Html>';
                    Messaging.SingleEmailMessage oneEmail = new Messaging.SingleEmailMessage();
                    //Making email address of dummy contact record inactive 
                    oneEmail.setTreatTargetObjectAsRecipient(false);
                    //Setting the setTargetObjectId to dummy contact id
                    if(!contactLIST.isEmpty()) {
                        oneEmail.setTargetObjectId(contactLIST[0].id);
                    }
                    oneEmail.setSaveAsActivity(false);
                    //Setting the WhatId to customobject Id so that merge fields in template gets rendered
                    oneEmail.setWhatId(request.Id);
                    oneEmail.setSubject('Materials of ' +request.Name+ ' is due for return on ' +request.DueDateofReturn__c);
                    //Set email body
                    oneEmail.setHtmlBody(bodyApplicant);
                    //set user email to send email
                    oneEmail.setToAddresses(new LIST<String>{request.CreatedBy.Email,request.Approver1__r.Email});
                    allSingleEmailLIST.add(oneEmail);
                }
                
            }
            if(!allSingleEmailLIST.isEmpty()) {
                Messaging.sendEmail(allSingleEmailLIST);
            }
        }  
    }
    /*Finish method for Batch Class*/
    public void finish(Database.BatchableContext bc){
        
    }
    /* Execute method for Schedule class */
    public void execute(SchedulableContext sc){
        Database.executeBatch(this);
    }
    /* method to schedule the batch according to the given CRON expression*/
    public void scheduleBatch(String jobName,String cron){
        System.schedule(jobName,cron, this);
    }
}