force-app/main/default/objects/IFv2_AdminOnly__c/IFv2_AdminOnly__c.object-meta.xml
<CustomObject>
    <description>Only to be used for the System Admin</description>
    <label>InsightFlow 2.0 Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InsightFlow 2.0 Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Active checkbox which holds the Out of Office settngs</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InsightFlow_2_0_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/WorkflowName__c.field-meta.xml
<CustomField>
    <fullName>WorkflowName__c</fullName>
    <description>Holds Workflow Name</description>
    <label>Workflow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFv2_BackToOfficeBatch.cls
/*******************************************************************************************************
* 
* @ Name :IFv2_BackToOfficeBatch
* @ Purpose : Class that collectss  users who are Back to Office and assigns their requests back.
* @ Author: Hanu Sanampudi
* @ Test Class Name : IFv2_BackToOfficeOutOfOfficeBatchV2test
*
*   Date        |  Developer Name                       |  Version      |  Changes
* ======================================================================================================
*   10-09-2019  |  hanumantharao.sanampudi@seg-automotive.com     |  1.0          |  Initial Version

*******************************************************************************************************/

global class IFv2_BackToOfficeBatch implements Database.Batchable<sObject> {
    
    String reassignmentLogId = Schema.SObjectType.IFv2_AdminOnly__c.getRecordTypeInfosByName().get('Reassignment Logs').getRecordTypeId();
    LIST<Id> backToOfficeuserIds = new LIST<Id>();	
    
    //Querying users who should be considered in reassignment and delegate assignment of approval requests
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String strQuery = '';
        if(Test.isRunningTest()){
            strQuery ='SELECT Id,Name,ConsiderInReassignmentBatch__c From User Where ConsiderInReassignmentBatch__c=true AND isActive=true AND Out_Of_Office__c =false limit 1';
        } else {
            strQuery ='SELECT Id,Name,ConsiderInReassignmentBatch__c From User Where ConsiderInReassignmentBatch__c=true AND isActive=true AND Out_Of_Office__c =false and id=\'0059E000008KfQ8QAK\'';
        }
        return Database.getQueryLocator(strQuery);
    }
    
    global void execute(Database.BatchableContext BC, LIST<User> usersList) {
        
        List<IFv2_AdminOnly__c> adminonlyRecords = new List<IFv2_AdminOnly__c>();
        
        if(!usersList.isEmpty()) {
            if(Test.isRunningTest()) {
                adminonlyRecords = [SELECT WorkflowName__c,User__c,createdbyid,Active__c,OwnerId From IFv2_AdminOnly__c limit 1];
            } else {
                adminonlyRecords = [SELECT WorkflowName__c,User__c,createdbyid,Active__c,OwnerId From IFv2_AdminOnly__c 
                                    Where recordtypeId=:reassignmentLogId AND WorkflowName__c!=Null                                                 
                                    AND User__c!=Null AND OwnerId IN : usersList];
            }
        }
        System.debug('Debug:: check for admin logs ***** Finished'+adminonlyRecords);
        if(!adminonlyRecords.isEmpty()) {
            System.debug('Debug:: adminonlyRecords*****' + adminonlyRecords);
            //Iterating and collecting the created by id and delegated id and allso workflow
            for(IFv2_AdminOnly__c admin : adminonlyRecords) {
                backToOfficeuserIds.add(admin.OwnerId);	
            } 
        }
        
        //Invoking Back To office
        if(!backToOfficeuserIds.isEmpty()) {
            OutOfOfficeAndBackToOfficeHelper.assignRequestsBack(backToOfficeuserIds, null);
        }
    }
    
    //Finish method
    global void finish(Database.BatchableContext BC) {
        //do nothing
    }
}