force-app/main/default/objects/IFv2_AdminOnly__c/IFv2_AdminOnly__c.object-meta.xml
<CustomObject>
    <description>Only to be used for the System Admin</description>
    <label>InsightFlow 2.0 Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InsightFlow 2.0 Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/HomeScreenCustomSettingId__c.field-meta.xml
<CustomField>
    <fullName>HomeScreenCustomSettingId__c</fullName>
    <description>This filed is  used to store home screen custom setting Id.</description>
    <inlineHelpText>This filed is  used to store home screen custom setting Id.</inlineHelpText>
    <label>Home Screen Custom Setting Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InsightFlow_2_0_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/recordTypes/Favorite.recordType-meta.xml
<RecordType>
    <fullName>Favorite</fullName>
    <active>true</active>
    <description>This record type is used for storing favorite on home page</description>
    <label>Favorite</label>
</RecordType>

force-app/main/default/objects/IFv2_HomeScreenTab__c/IFv2_HomeScreenTab__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Tabs for applications to be displayed on Home screen</description>
    <label>Home Screen Tab</label>
</CustomObject>

force-app/main/default/classes/IFv2_GeneralHomeControllerTest.cls
/*******************************************************************************************************
* 
* @ Name		:  IFv2_GeneralHomeControllerTest
* @ Purpose		:  Test class for IFv2_GeneralHomeController
* @ Author		:  Prasad Vivek
* @ Class  		:  IFv2_GeneralHomeController
*
*   Date            |  Developer Name               	|  Version      |  Changes
* ======================================================================================================
*   22-06-2019      |  vivek.kothalanka@absyz.com    	|  1.0          |  Added favorite logic.

*******************************************************************************************************/
@isTest
public class IFv2_GeneralHomeControllerTest {
    
    public static TestMethod void  getHomeScreenTabsTest(){
        LIST<SObject> sbojectLIST = new LIST<SObject>();
        LIST<IFv2_HomeScreenTab__c> customsettingLIST = new LIST<IFv2_HomeScreenTab__c>();
        customsettingLIST = IFv2_testDataUtility.createHomeScreenCustomSettings();
        
        insert customsettingLIST;
        
        LIST<IFv2_AdminOnly__c> adminOnlyLIST = new LIST<IFv2_AdminOnly__c>();
        
        String favoriteRecordTypeId = Schema.SObjectType.IFv2_AdminOnly__c.getRecordTypeInfosByName().get('Favorite').getRecordTypeId();
        
        adminOnlyLIST = IFv2_testDataUtility.adminOnlyRecords();
        system.assertEquals(true, adminOnlyLIST.size()>0);
        
        for(IFv2_AdminOnly__c adminonly : adminOnlyLIST) {
            
            adminonly.RecordTypeId = favoriteRecordTypeId;
            adminonly.User__c = userInfo.getUserId();
        }
        insert adminOnlyLIST;
        
        sbojectLIST = IFv2_GeneralHomeController.getHomeScreenTabs();
    }
    public static TestMethod void updateFavoriteTest(){
        
        LIST<IFv2_HomeScreenTab__c> customsettingLIST = new LIST<IFv2_HomeScreenTab__c>();
        customsettingLIST = IFv2_testDataUtility.createHomeScreenCustomSettings();
        
        insert customsettingLIST;
        
        LIST<IFv2_AdminOnly__c> adminOnlyLIST = new LIST<IFv2_AdminOnly__c>();
        
        String favoriteRecordTypeId = Schema.SObjectType.IFv2_AdminOnly__c.getRecordTypeInfosByName().get('Favorite').getRecordTypeId();
        
        adminOnlyLIST = IFv2_testDataUtility.adminOnlyRecords();
         system.assertEquals(true, adminOnlyLIST.size()>0);
        
        for(IFv2_AdminOnly__c adminonly : adminOnlyLIST) {
            
            adminonly.RecordTypeId = favoriteRecordTypeId;
            adminonly.HomeScreenCustomSettingId__c = customsettingLIST[0].Id;
            adminonly.User__c = userInfo.getUserId();
        }
        insert adminOnlyLIST;
        
        IFv2_GeneralHomeController.updateFavorite(customsettingLIST[0].Id,true);
    }
    
    public static TestMethod void updateFavoriteTestTwo(){
        
        LIST<IFv2_HomeScreenTab__c> customsettingLIST = new LIST<IFv2_HomeScreenTab__c>();
        customsettingLIST = IFv2_testDataUtility.createHomeScreenCustomSettings();
        
        insert customsettingLIST;
        
        LIST<IFv2_AdminOnly__c> adminOnlyLIST = new LIST<IFv2_AdminOnly__c>();
        String favoriteRecordTypeId = Schema.SObjectType.IFv2_AdminOnly__c.getRecordTypeInfosByName().get('Favorite').getRecordTypeId();
        
        adminOnlyLIST = IFv2_testDataUtility.adminOnlyRecords();
         system.assertEquals(true, adminOnlyLIST.size()>0);
        
        for(IFv2_AdminOnly__c adminonly : adminOnlyLIST) {
            
            adminonly.RecordTypeId = favoriteRecordTypeId;
        }
        insert adminOnlyLIST;
        
        IFv2_GeneralHomeController.updateFavorite(customsettingLIST[0].Id,true);
    }
    
}