force-app/main/default/objects/IFv2_AdminOnly__c/IFv2_AdminOnly__c.object-meta.xml
<CustomObject>
    <description>Only to be used for the System Admin</description>
    <label>InsightFlow 2.0 Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InsightFlow 2.0 Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Active checkbox which holds the Out of Office settngs</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InsightFlow_2_0_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/fields/WorkflowName__c.field-meta.xml
<CustomField>
    <fullName>WorkflowName__c</fullName>
    <description>Holds Workflow Name</description>
    <label>Workflow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFv2_AdminOnly__c/recordTypes/OutOfOfficeLogs.recordType-meta.xml
<RecordType>
    <fullName>OutOfOfficeLogs</fullName>
    <active>true</active>
    <label>OutOfOfficeLogs</label>
</RecordType>

force-app/main/default/classes/IFv2_BackToOfficeOutOfOfficeBatchV2.cls
/*******************************************************************************************************
* 
* @ Name :IFv2_BackToOfficeOutOfOfficeBatchV2
* @ Purpose : Class that collectss  users who are out of office assigns their requests to delegated approvers
* @ Author: Naga Sai
* @ Test Class Name : IFv2_BackToOfficeOutOfOfficeBatchV2test
*
*   Date        |  Developer Name                       |  Version      |  Changes
* ======================================================================================================
*   08-03-2018  |  nagasai.chalamalasetti@absyz.com     |  1.0          |  Initial Version

*******************************************************************************************************/

global class IFv2_BackToOfficeOutOfOfficeBatchV2 implements Database.Batchable<sObject> {
    
    //Global Variables
    SET<Id> outOfOfficeUserIds = new SET<Id>(); 
    LIST<Id> backToOfficeuserIds = new LIST<Id>();
    
    //Querying users who should be considered in reassignment and delegate assignment of approval requests
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String outofofficelogsrecordtypeid = Schema.SObjectType.IFv2_AdminOnly__c.getRecordTypeInfosByName().get('OutOfOfficeLogs').getRecordTypeId();
        String   query ='SELECT WorkflowName__c,User__c,createdbyid,Active__c'+
            ' FROM IFv2_AdminOnly__c a WHERE  recordtypeid=:outofofficelogsrecordtypeid  '+ 
            'AND createdbyid not in :outOfOfficeUserIds AND createdbyid not in :backToOfficeuserIds '+
            'AND WorkflowName__c!=Null AND User__c!=Null and ((a.LastModifiedDate = TODAY AND HOUR_IN_DAY(a.LastModifiedDate) > 1) OR Active__c=true)';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, LIST<IFv2_AdminOnly__c> adminonlyRecords) {
        if(!adminonlyRecords.isEmpty()) {
            String workflow;
            MAP<String,String> delegatedIdworkflownameMap = new MAP<String,String>();
            
            //Iterating and collecting the created by id and delegated id and allso workflow
            for(IFv2_AdminOnly__c admin : adminonlyRecords) {
                //Collecting out of office userids
                if(admin.Active__c) {
                    outOfOfficeUserIds.add(admin.CreatedById);
                    delegatedIdworkflownameMap.put(admin.WorkflowName__c, admin.User__c);
                } else {
                    //collecting back to office user ids
                    backToOfficeuserIds.add(admin.CreatedById);
                    workflow = admin.WorkflowName__c ;
                }
            }
            //Invoking Out of office
            if(!outOfOfficeUserIds.isEmpty()) {
                IFv2_TriggerHandler.TransferApproverToDelegatedUserv1(outOfOfficeUserIds, delegatedIdworkflownameMap);
            }
            //Invoking Back To office
            if(!backToOfficeuserIds.isEmpty()) {
                IFv2_TriggerHandler.AssignRequestsBack(backToOfficeuserIds, workflow);
            }
        }
    }
    
    //Finish method
    global void finish(Database.BatchableContext BC) {
        //do nothing
    }
}